### ISSUE TITLE
Compatibility Issue with First Aid

### ISSUE THREAD

**Issue by ConqAra** [Cazsius/Spice-of-Life-Carrot-Edition#102]
Using both mods causes you to spawn with no health. And when a heart is gained, it completely depletes all health from the player, but somehow doesn't kill them (until the player takes ANY form of damage after, thus dying instantly). In the First Aid interface, the entire body becomes red showing 0 hearts on every single part of the body. I am posting this because someone already posted this problem 2 weeks ago to the First Aid github, but was wondering if this mod was partly responsible since First Aid usually works with additional health to your character. The link to this problem is below containing the logs.

https://github.com/ichttt/FirstAid/issues/111

**Comment by ConqAra** [comment]
This problem occurs as soon as you spawn for the very first time. It fixes itself after the player dies, but once the player gets another heart (from this mod) the same problem will repeat.

**Comment by juliand665** [comment]
Oh, fun. So this is still an issue, I guess. We've had [reports of this](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues?q=label%3Acompatibility+) previously, but they all ended up going inactive. I might have to just open an issue on their tracker to figure out a solution with them.

**Comment by juliand665** [comment]
[#115 on their tracker](https://github.com/ichttt/FirstAid/issues/115), if you want to follow the conversation.
