### ISSUE TITLE
Можно ли получить больше сердец?

### ISSUE THREAD

**Issue by KorumoVago227** [Cazsius/Spice-of-Life-Carrot-Edition#109]
![image](https://user-images.githubusercontent.com/83035011/115770403-55462300-a3b5-11eb-895d-e3944a442fa2.png)
Выдаёт такую ошибку,как то можно починить?

**Comment by juliand665** [comment]
This is not an error. The mod has been configured to not give you any more hearts than you've already received. You can change this:

`<minecraft folder>/saves/<world folder>/serverconfig/solcarrot-server.toml`:
```toml
[milestones]
	# ...
	milestones = [5, 10, 15, 20, 25] # <- change this
	# ...
# ...
```

For example, you could change it to this:
```toml
	milestones = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]
```

You could also change `heartsPerMilestone` so you don't get as many hearts. Or you could also change it to `[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]`, or anything you want.

**Comment by KorumoVago227** [comment]
> Это не ошибка. Мод настроен так, чтобы не давать вам сердец больше, чем вы уже получили. Вы можете изменить это:
> 
> `<minecraft folder>/saves/<world folder>/serverconfig/solcarrot-server.toml`:
> 
> ```toml
> [ вехи ]
> 	 # ... 
> 	вехи = [ 5 , 10 , 15 , 20 , 25 ] # <- изменить это 
> 	# ... 
> # ...
> ```
> 
> Например, вы можете изменить его на это:
> 
> ```toml
> 	вехи = [ 5 , 10 , 15 , 20 , 25 , 30 , 35 , 40 , 45 , 50 , 55 , 60 , 65 , 70 , 75 , 80 , 85 , 90 , 95 , 100 ]
> ```
> 
> Вы также можете измениться, `heartsPerMilestone`чтобы не получить столько сердец. Или вы также можете изменить его на `[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]`или что угодно.

Thank you
