### ISSUE TITLE
[bug] Food not registering as eaten

### ISSUE THREAD

**Issue by ghost** [Cazsius/Spice-of-Life-Carrot-Edition#11]
Minecraft Version: 1.12.2
Forge Version: 14.23.0.2512
Mod Version: 1.2.0
Applecore Version: 2.2.2

`# Configuration file

general {
    # An array containing the milestones: How many unique foods you must eat to get the milestone bonus (defined above). Note that this represents the TOTAL number of foods needed; not the foods since the last milestone!
    I:"Milestone amounts" <
		3
		5
		8
		12
		18
		26
		36
		48
		65
		93
		121
     >

    # Number of hearts you spawn with. [range: 1 ~ 30, default: 10]
    I:defaultHeartCount=8

    # Number of hearts you gain per milestone. [range: 1 ~ 30, default: 2]
    I:heartsPerMilestone=1

    # Add tooltips to foods to indicate if they have been eaten? [default: true]
    B:isFoodTooltipEnabled=true
}`

After eating a food item, the tooltip does not change, nor does reaching a milestone seem to register (i.e. hearts do not increase and no message is displayed). I'm not sure whether another mod I have is interfering with this, or whether it is an anomaly from SOL Carrot itself.

**Comment by antoinegag** [comment]
If you think a mod might be interfering maybe list them :P

**Comment by ghost** [comment]
Sure.

### Client Mods
Better Placement
CleanView
Dynamic Surroundings
Enchantment Descriptions
Just Enough Pattern Banners
Just Enough Resources
NoNausea
Optifine
Pick Block Plus
ReAuth
Smart HUD
Sound Filters
StepUp

### Client & Server Mods
Additional Banners
Advanced Hook Launchers
Akashic Tome
Antique Atlas
AppleCore
Architect
AutoRegLib
Bed Bugs
BetterFPS
Better Builder's Wands
Better With Mods
BlockCraftery
Bottled Milk
CapabilityProxy
Carry On
Colossal Chests
Comforts
CoroUtil
Corpse Complex
CraftTweaker
Creeper Confetti
Cyclops Core
DegradeExplodedBlocks
Diet Hoppers
Dynamic Trees
EluLib
Embers
Enchanting Bottles
Extra Ambiance
Fairy Lights
FoamFix (Anarchy)
ForgeEndertech
Gold Cauldron
Hardcore Revival
Hopper Ducts
InControl!
Initial Inventory
Just Enough Items
Lapis Stays In The Enchanting Table
LootTweaker
Mana Wells Revived
Mending Fix
Minecart AI Fix
Misty World
MTLib
Nemesis System
NetherEx
NoDamI
Ocean Floor
Ore Excavation
Passable Leaves
Photoptics
Progressive Difficulty
Quark
Redstone Paste
Roots
RTFM
Ruins
Rustic
SaltyMod
Simulated Nights
Skyblocks
Spice of Life: Carrot Edition
Stalker Creepers
Stellar API
Storage Boats
Structured Crafting
SwingThroughGrass
The Twilight Forest
The Weirding Gadget
TorchMaster
ToroTraits
TschippLib
V-Tweaks
Villager Trade Tables
Waddles
Wearable Backpacks
With Sprinkles
Zombie Awareness


### Server Mods
AI Improvements
Chunk-Pregenerator
Friendly Fire
Login Shield
Quick Leaf Decay
Tick Dynamic

**Comment by Cazsius** [comment]
This is not an issue with SOL:Carrot itself, until it can be reproduced, marking invalid.
