### ISSUE TITLE
[Feature Request] Add the three lunch boxes from regular Spice of Life

### ISSUE THREAD

**Issue by Kaligraphy22** [Cazsius/Spice-of-Life-Carrot-Edition#112]
As the title says. Was watching a youtuber playing the Engineer's Life 2 modpack and noticed the lunch boxes. Checked the mod list and it comes from the regular Spice of Life (and it's in the Potato edition). Always nice to be able to clear space in inventories and if I remember correctly, you can eat straight from the lunch box without removing the food from it.

**Comment by juliand665** [comment]
See #96—out of scope for this mod. This reminds me, I should pin a relevant issue.

**Comment by Kaligraphy22** [comment]
Ok, read #96 and #44 from there. I should have searched to see if someone brought up this topic before. Haven't found a lunch box mod so I'd thought I'd ask here. No worries but thank you for replying. :)
