### ISSUE TITLE
1.16.5 Milestones go to 400, but hearts capped to 10 in the book.

### ISSUE THREAD

**Issue by OddJarro** [Cazsius/Spice-of-Life-Carrot-Edition#114]
Is this an issue of not tracking, will I keep getting hearts? Im not sure what is going on, but the book tells me I can only get 10 hearts when the max should be somewhere around 28.
![204601944_1206225183173793_4699274078060602108_n](https://user-images.githubusercontent.com/86746544/124029686-a163a400-d9b2-11eb-8740-a08a4683a40d.jpg)

**Comment by juliand665** [comment]
Milestones (that give you more hearts) are not defined by a set distance. Instead, you configure specific milestones, and the default config only has five: 5, 10, 15, 20, 25. Past that, you can't earn any more hearts. You'll have to manually add more in the (server-side, stored in the world's folder) config.

**Comment by OddJarro** [comment]
Would you be able to give me a step by step because I tried that and the milestones go up to 400, but for some reason when we start the server it only says 10

**Comment by juliand665** [comment]
You're likely editing an incorrect config file. Try changing an existing milestone (like the 25 one)—I bet it won't have any effect! Can you share your config file here, as well as the path to it? (e.g. minecraft/saves/xyz/serverconfig/solcarrot-server.toml)

You should even be able to edit the config while the game is running and have it automatically update in-game shortly after you save.
