### ISSUE TITLE
Can't use /foodlist clear on yourself if not opped

### ISSUE THREAD

**Issue by jinkhya** [Cazsius/Spice-of-Life-Carrot-Edition#117]
Hello, I dunno if that's intended but you can't clear your foodlist if not opped. The message tells you you can't apply the command to other players even though I specified my own name. 
It'd be cool to be able to do it yourself without having to ask admins on a server when you've played a pack and want to restart.
Thanks in advance.
Jin

**Comment by juliand665** [comment]
Hmm, does it work if you just don't specify a player at all? Just running `/foodlist clear` with no arguments.

**Comment by jinkhya** [comment]
It doesn't either, `/foodlist clear` gives the same error message "you do not have the permissions necessary to apply this command to other players"

**Comment by juliand665** [comment]
Wait, I think I know what's going wrong… Is it possible you can clear other players' lists but not your own? I think I inverted a check lmao

https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/blob/f4af6e9abc81882c2ca65fc77b24c040c96255ed/src/main/java/com/cazsius/solcarrot/command/FoodListCommand.java#L75-L76

**Comment by juliand665** [comment]
Can you try if it's still wrong with this version? You'll have to put it on the server (the client shouldn't matter).

[SoL-Carrot-1.16.5-1.10.1.jar.zip](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/6951641/SoL-Carrot-1.16.5-1.10.1.jar.zip)

**Comment by jinkhya** [comment]
That fixed it thank you ! :D

**Comment by juliand665** [comment]
Glad to hear it! Will upload the update to CurseForge now.
