### ISSUE TITLE
[1.16.5]When you die in the Nether, the server and the client need to restart.

### ISSUE THREAD

**Issue by nin8995** [Cazsius/Spice-of-Life-Carrot-Edition#119]
It happens also when you go through End Portal in the End and maybe other interdimensional process of teleporting a player by killing him/her. 
I'm using Mohist and running Stacia Expert.
Here is logs after I died in the Nether.
[logs.txt](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/7233773/logs.txt)

**Comment by juliand665** [comment]
If this doesn't happen with a standard Forge server, it's Mohist's fault (and their job to fix) instead of ours. Feel free to report it to them!
