### ISSUE TITLE
Backpacked incompatibility.

### ISSUE THREAD

**Issue by antauriprime** [Cazsius/Spice-of-Life-Carrot-Edition#122]
When both **Spice of Life: Carrot Edition** and **Backpacked** are present the Player can't respawn after dying.
Respawn button does nothing. The only way to respawn is to disable one or the other.

Demo:

https://user-images.githubusercontent.com/30935221/151409114-42f85198-d639-4dc9-8233-50714ebac6c1.mp4

**Comment by zachsai** [comment]
I have the same issue^

**Comment by juliand665** [comment]
Fixed on their end: https://github.com/MrCrayfish/Backpacked/issues/71
