### ISSUE TITLE
(1.12.2) when I die, I should eat at least 1 food in order to get back my hp by milestones

### ISSUE THREAD

**Issue by rebarakuk** [Cazsius/Spice-of-Life-Carrot-Edition#123]
If I don't eat any food after respawn, I lose my hp

Minecraft 1.12.2
Forge 14.23.5.2860
spice of life carrot edition 1.8.4
the spice of life 1.3.12

"reset on death" in config is 'false'

**Comment by juliand665** [comment]
First of all, you're aware Carrot Edition does not require standard Spice of Life alongside it, right?

I'm not quite sure how to interpret your issue. Once you do eat something, does your HP return?

**Comment by rebarakuk** [comment]
> First of all, you're aware Carrot Edition does not require standard Spice of Life alongside it, right?
> 
> I'm not quite sure how to interpret your issue. Once you do eat something, does your HP return?

Yes my hp returns, but not filled

**Comment by juliand665** [comment]
Does it still happen without classic spice of life? i.e. just carrot edition (& applecore); no other mods at all.

**Comment by rebarakuk** [comment]
No. The unfilled hp comes back

**Comment by juliand665** [comment]
So it looks like this is an incompatibility between spice of life carrot edition and classic edition then. Seeing as this is 1.12 and thus increasingly outdated, I’m happy to just say “oh well, guess you can’t have both.”
