### ISSUE TITLE
Frequently My Milestones Reset | Version 1.10.1 [FORGE]

### ISSUE THREAD

**Issue by FalsifiedKing** [Cazsius/Spice-of-Life-Carrot-Edition#125]
[milestones]
	#Number of hearts you start out with.
	#Range: 0 ~ 1000
	baseHearts = 10
	#Number of hearts you gain for reaching a new milestone.
	#Range: 0 ~ 1000
	heartsPerMilestone = 2
	#A list of numbers of unique foods you need to eat to unlock each milestone, in ascending order. Naturally, adding more milestones lets you earn more hearts.
	milestones = [5, 10, 15, 20, 25, 30, 35. 40, 45, 50, 60, 70, 80, 90, 100, 120, 140, 160, 180, 200, 240, 280, 320, 360, 400]

[filtering]
	#Foods in this list won't affect the player's health nor show up in the food book.
	blacklist = []
	#When this list contains anything, the blacklist is ignored and instead only foods from here count.
	whitelist = []
	#The minimum hunger value foods need to provide in order to count for milestones, in half drumsticks.
	#Range: 0 ~ 1000
	minimumFoodValue = 1

[miscellaneous]
	#Whether or not to reset the food list on death, effectively losing all bonus hearts.
	resetOnDeath = false
	#If true, eating foods outside of survival mode (e.g. creative/adventure) is not tracked and thus does not contribute towards progression.
	limitProgressionToSurvival = false

**(THIS IS MY FILE)**

**Comment by juliand665** [comment]
Where are you putting this file? Serverconfig is per-world by default, so I'm assuming your talking about the defaultconfigs folder. I guess forge is doing something strange there?

Makes no sense that it'd overwrite your changes; I imagine shipping a ready-made instance with configs but no worlds is basically the modpack author pipeline.

**Comment by FalsifiedKing** [comment]
I am confused of what you mean. Sorry, I am not that experienced in this. I make a mistake in the file when submitting let me change it... (I have 185 mods...)

Do you know what I could do to prevent this?


Bolded message from last title: **(It seems to reset if there are no worlds in singleplayer or when a singleplayer world is deleted)**

**Comment by juliand665** [comment]
Oh! You have a mistake in your milestones list. I bet the output log would contain an error report or something, but you can't really be expected to look there.
<img width="425" alt="image" src="https://user-images.githubusercontent.com/827762/162534775-257d929c-167c-42b0-9eef-0e3fee0348a3.png">

**Comment by FalsifiedKing** [comment]
I believe that is it, but I still do not know how it could have done this repeatedly. I will reinstall the mod and get back to you.
**(Sorry for the late response)**

- Update: When I install the mod it does not give me the option to change the milestones...
