### ISSUE TITLE
Player must have food capability attached, but none was found.

### ISSUE THREAD

**Issue by border999** [Cazsius/Spice-of-Life-Carrot-Edition#128]
[latest.log](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/8645562/latest.log)
Tried to log into my world and it seems like it's forgotten the information about food capability or it's not saving properly.
The version is SoL-Carrot-1.18.1-1.12.0

**Comment by juliand665** [comment]
This seems to be happening in a relatively large modpack. Can you try copying the world to an instance with just our mod and launching that to see if it still happens? If it works there, is your food data reset or did it survive? Either way, this is likely an incompatibility with another mod.

**Comment by border999** [comment]
I have a few mods that alter my health and food in some ways. Mods such as Gluttony+2.0.2 and MaxHealthFix-Forge-1.18.2-5.0.1

**Comment by juliand665** [comment]
Good idea, those may be conflicting. As I said, could you try isolating it to SoL: Carrot? If it doesn't break with just our mod, try re-adding those others you think might cause issues and see if that breaks it.

**Comment by border999** [comment]
It looks like this issue isn't always happening. The only thing I know the events had in common was that I died and crashed before I could hit respawn. Does that help? Is that space between being dead and respawning important?

**Comment by juliand665** [comment]
I wouldn't expect it to matter? If anything, it's whether or not you close the world/game in between, but idk.

Anyway, it would really help diagnose this issue if you could isolate it to as few mods as possible.

**Comment by border999** [comment]
The issue isn't happening anymore. Here were the circumstances that triggered the crash. I was batting an Ars Nouveau wizard and, if memory serves, I was struck by lighting to death both times. Crashed on the death screen. This either requires a very specific set of things to happen for it to occur, or it was a fluke. It happened at least twice, so I know it can be repeated.

**Comment by juliand665** [comment]
Ah funky, a classic Heisenbug. I'll close it for now unless you or someone else finds out more :)

**Comment by TristonWasik** [comment]
this is still very much an issue in the terralux: a new experience pack FYI. has happened to 3 different players on my server at this point
