### ISSUE TITLE
/sizefoodlist won't work without elevated permissions

### ISSUE THREAD

**Issue by Cazsius** [Cazsius/Spice-of-Life-Carrot-Edition#13]
Won't work on 1.11.+ 1.12

**Comment by Toperoco** [comment]
Any update here?

**Comment by Cazsius** [comment]
Plan to be looking into a bunch of issues this weekend, so hopefully by the end of the week it will be fixed.

**Comment by kwpugh** [comment]
Any news on this?

**Comment by Cazsius** [comment]
Finally fixed, pushing build now.
