### ISSUE TITLE
Bug minecraft:air?

### ISSUE THREAD

**Issue by ncottrill** [Cazsius/Spice-of-Life-Carrot-Edition#130]
This message crops up on occasion on the server 

[08.06 15:38:27] [Server] [Server thread/WARN] [solcarrot/]: attempting to load item into food list that is no longer edible: minecraft:air (ignoring in case it becomes edible again later) 

What is the meaning of this warning?

**Comment by juliand665** [comment]
Huh! Looks like something made the mod think you ate an empty stack and add that to someone's list of eaten foods. Now whenever it decodes that food list, it realizes the item is not edible. This can also happen when mod updates make something no longer edible, so this is just the general warning.

I first thought what's happening was that this modded item somehow empties its own stack when eaten before our mod takes note of what it was. However, I just checked the code, and it only adds items if they're edible. So either something somehow made air edible (and later stopped), or something else is going on…

If the warning is too annoying, you could head into the player data with an NBT editor (it should be printed on login and maybe respawn, so you could tell which player it is) and remove the entry `minecraft:air` from the capability `solcarrot:food_list` (I believe). If you're not comfortable with that, I think your best bet is just to ignore it?

**Comment by ncottrill** [comment]
Thank you for the reply!  Tracking this down will be a challenge. We have 126 mods. So, I think I will chose to ignore it! I was thinking that it would be nice to have a configurable ignore list in sol. Then, I could just add "air" and sol would ignore that entry.
