### ISSUE TITLE
Suggestions: Disable nourishment in config

### ISSUE THREAD

**Issue by MattB70** [Cazsius/Spice-of-Life-Carrot-Edition#131]
My pack disables hunger, and as such the nourishment effect does nothing to the player, but it does effect the HUD, adding a hunger bar in the UI where it should not be. Being able to disable the nourishment effect would help me quite a bit as it's the "correct" way of solving this issue.

**Comment by juliand665** [comment]
I think you've gotten us confused with another mod. The only effect we have is permanent additional hearts.

**Comment by MattB70** [comment]
Yep! I forgot about the effects that Farmer's Delight adds. Their config had what I needed.
