### ISSUE TITLE
Whitelist question

### ISSUE THREAD

**Issue by meBVH** [Cazsius/Spice-of-Life-Carrot-Edition#137]
I'm trying to add  foods in the whitelist but there is a breakdown when creating a new world.
[crashreport.txt](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/9330824/crashreport.txt)

Here is the severconfig file
[milestones]
	#Number of hearts you start out with.
	#Range: 0 ~ 1000
	baseHearts = 6
	#Number of hearts you gain for reaching a new milestone.
	#Range: 0 ~ 1000
	heartsPerMilestone = 2
	#A list of numbers of unique foods you need to eat to unlock each milestone, in ascending order. Naturally, adding more milestones lets you earn more hearts.
	milestones = [5, 10, 15, 20, 25, 30, 35, 40, 45]

[filtering]
	#Foods in this list won't affect the player's health nor show up in the food book.
	blacklist = []
	#When this list contains anything, the blacklist is ignored and instead only foods from here count.
	whitelist = [minecraft:enchanted_golden_apple, alexmobs:rainbow_jelly, alexmobs:sopa_de_macaco, alexmobs:kangaroo_burger, famersdelight:chicken_soup, famersdelight:fried_rice, famersdelight:baked_cod_stew, famersdelight:noodle_soup, famersdelight:roasted_mutton_chops, famersdelight:vegetable_noodles, famersdelight:squid_ink_pasta, famersdelight:grilled_salmon, famersdelight:roast_chicken, famersdelight:stuffed_pumpkin, famersdelight:honey_glazed_ham, famersdelight:shepherds_pie, famersdelight:hamburger, famersdelight:fish_stew, famersdelight:smoked_ham, famersdelight:bacon_sandwich, famersdelight:beef_stew, famersdelight:vegetable_soup, famersdelight:pasta_with_meatballs, famersdelight:pasta_with_mutton_chop, famersdelight:steak_and_patatoes, famersdelight:ratatouille, famersdelight:barbecue_stick, famersdelight:dumplings, famersdelight:fruit_salad, famersdelight:mixed_salad, famersdelight:nether_salad, nethersdelight:plate_of_stuffed_hoglin_ham, nethersdelight:plate_of_stuffed_hoglin_roast, nethersdelight:magma_gelatin, nethersdelight:grilled_strider, nethersdelight:nether_skewer, famersrespite:blazing_chill, famersrespite:tea_curry, twilightdelight:aurora_ice_cream, twilightdelight:grilled_ghast, twilightdelight:fiery_snakes, gobberdelight:blue_burger, gobberdelight:red_burger, gobberdelight:end_ice_cream, gobberdelight:end_cake]
	#The minimum hunger value foods need to provide in order to count for milestones, in half drumsticks.
	#Range: 0 ~ 1000
	minimumFoodValue = 1

[miscellaneous]
	#Whether or not to reset the food list on death, effectively losing all bonus hearts.
	resetOnDeath = false
	#If true, eating foods outside of survival mode (e.g. creative/adventure) is not tracked and thus does not contribute towards progression.
	limitProgressionToSurvival = false

**Comment by meBVH** [comment]
game version：1.18.2
mod version: SoL-Carrot-1.18.1-1.12.0

**Comment by juliand665** [comment]
Your error log looks fucked up beyond belief, but the problem is clear from the config file alone: you need to put the item IDs in quotes: `whitelist = ["minecraft:enchanted_golden_apple", "alexmobs:rainbow_jelly", ...]`

**Comment by meBVH** [comment]
Thx , and I recommend adding some examples to the config file , because people around me don't know how to use it.
