### ISSUE TITLE
The Chat-Bug

### ISSUE THREAD

**Issue by ghost** [Cazsius/Spice-of-Life-Carrot-Edition#14]
Hey im here now :D

Here in this issue (https://minecraft.curseforge.com/projects/modern-skyblock-2/issues/332) ive problem with the my food when i eat it. it talsk to me alltime in chat ive eaten more then 100 foods, with all what i eat

I made a video for u:
https://pudding.tk/xy1taxqN.mp4

greetz :D

**Comment by Cazsius** [comment]
I've not been able to replicate this on any later version, appears to be fixed on new versions of mod.
