### ISSUE TITLE
Compatibility-ish. 

### ISSUE THREAD

**Issue by AefRal** [Cazsius/Spice-of-Life-Carrot-Edition#140]
I think it's this mod that makes the health and food bars look like gems.
https://www.curseforge.com/minecraft/mc-mods/quest-plaques

I'm not sure which mod would need to update for this.
https://github.com/AHilyard/QuestPlaques/issues/6

The extra hearts are on top of the first health bar like normal, but I think they should be gems to match.
Just, well, gems of a different colour. Like how the second health bar is orange hearts. 
To match, they should be orange gems. 
![Gem Hearts and Food](https://user-images.githubusercontent.com/68062495/191877717-36f855a0-2926-476e-8dcd-b72a65ba68cd.png)

**Comment by juliand665** [comment]
The overlaying hearts display is not part of our mod. You're likely using Mantle, which is mostly a library mod but also performs this change.

**Comment by AefRal** [comment]
Thank you for the info.
