### ISSUE TITLE
Not working with Hunger Reworked

### ISSUE THREAD

**Issue by romaust** [Cazsius/Spice-of-Life-Carrot-Edition#141]
Dont tracking what i eat with [Hunger Reworked](https://www.curseforge.com/minecraft/mc-mods/hunger-reworked)

Game version 1.18.2

**Comment by juliand665** [comment]
It looks like the event we're using to get notified of foods being eaten:
https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/blob/30e76bd0ec3b7db3753cc6455022514e1ff79a35/src/main/java/com/cazsius/solcarrot/tracking/FoodTracker.java#L25
is being [canceled](https://github.com/Adneths/hunger-reworked/blob/a9f2c50c7e8e554174d4ae00080d8bdfedf4ffc3/src/main/java/me/adneths/hunger_reworked/event/FoodEventHandler.java#L161) by this mod.

I think it's up to them to fix this, especially considering the popularity difference. Feel free to link to this issue when filing one with them!
