### ISSUE TITLE
Allow grouping foods for milestones instead of eating a set number of foods

### ISSUE THREAD

**Issue by Hexicube** [Cazsius/Spice-of-Life-Carrot-Edition#145]
Currently milestones are just eat X unique foods, it would be nice if instead I could group foods (such as every raw crop or every poisonous food) and have the completion of each group grant a bonus (1 heart for all poisonous, 2 hearts for all crops, 5 hearts for enchanted apple, etc.).

Not sure how this would work for a .toml config file, but I assume you could have something like:

`[milestones]
	baseHearts = 10
	groupMode = true

[milestones.crops]
	name = "Crops"
	hearts = 2
	food = ["minecraft:carrot", "minecraft:potato", "minecraft:beetroot"]`

Ideally this would also amend the food book to say things like "Categories: 2/5" instead of the milestone graph and "Crops: 1/3" (name specified in config) instead of "Not yet tasted: 5". Probably also "Categories" pages showing how many hearts each one grants and their progress.

This would also implicitly replace blacklist and whitelist since each group has its own whitelist.

**Comment by juliand665** [comment]
This would be a pretty major change! A cool idea, but I can't say it's likely to happen any time soon for this specific mod; I'm really just maintaining it and porting to new MC versions at this point.

**Comment by Hexicube** [comment]
I've ended up making a fork for this, the scale of the change really puts it out-of-scope for what Carrot edition is since you kinda have to manually specify every food and there's no simple milestones anymore.
