### ISSUE TITLE
Ignoring meta data

### ISSUE THREAD

**Issue by TheLimePixel** [Cazsius/Spice-of-Life-Carrot-Edition#15]
When you eat anything that has a certain item id, everything with that id, but with a different meta data will be counted as eaten. A good example is fish; if you eat one type of fish, all of them will count as eaten as they have the same item id

**Comment by Cazsius** [comment]
This is fixed in our development build, when tested and released, this will be fixed.

**Comment by EmosewaGamer** [comment]
After further inspection, it seems to be an issue only with the tooltip.

**Comment by Cazsius** [comment]
Releasing Fix tonight
