### ISSUE TITLE
How to use whitelist?

### ISSUE THREAD

**Issue by xDanilor** [Cazsius/Spice-of-Life-Carrot-Edition#152]
hello, i'd like to write an item whitelist for spice of life. When starting the server, it will delete every change i do so i guess i'm not writing in the correct way. I'm writing "food tag" (like: chicken_sandwich) and then comma after the name and then an empty space. (so for example: chicken_sandwich, hamburger...).
What's the correct way of writing the whitelist?

**Comment by juliand665** [comment]
(asked & answered on discord)
