### ISSUE TITLE
How do I get health directly through a command?

### ISSUE THREAD

**Issue by QianMuu** [Cazsius/Spice-of-Life-Carrot-Edition#153]
I want a specific player to get 20 health points directly,
Instead of letting it build up slowly through the food.
How do I get health directly through a command?

**Comment by juliand665** [comment]
We don't have functionality for that; added health is based entirely on unique foods eaten. You could just hop into creative mode and eat a bunch of foods? Or use another mod that lets you add extra health—maybe there's even a vanilla command for it?
