### ISSUE TITLE
Compatibility problem between Spice of Life Carrot edition and Sophisticated Backpacks

### ISSUE THREAD

**Issue by gaminggirl** [Cazsius/Spice-of-Life-Carrot-Edition#159]
Compatibility problem between Spice of Life Carrot edition and Sophisticated Backpacks after release of sophisticatedcore-1.20.1-0.6.35.726.jar

Until that version released ths Spice of Life book counted up when one ate food, after this update it only counts up if eating from inventory. 

Solcarrot edition: solcarrot-1.20.1-1.15.1
Minecraft edition: 1.20.1

**Comment by juliand665** [comment]
Great work figuring out the specific version that introduced this issue! Did you report it to Sophisticated Backpacks as well? I'm curious what they have to say about it since it's their change that triggered it.

**Comment by gaminggirl** [comment]
> Great work figuring out the specific version that introduced this issue! Did you report it to Sophisticated Backpacks as well? I'm curious what they have to say about it since it's their change that triggered it.

Yes I reported it both here and on Sophisticated Core, wasn't sure who I was supposed to go to.

**Comment by gaminggirl** [comment]
Problem is now fixed in Sophisticated Core and everything works again. So no actions needed. This post can be closed without any action. Sorry for the unnecessary post.

**Comment by juliand665** [comment]
Great! Thanks for letting us know.
