### ISSUE TITLE
Issue with X multiplier text position (multihotbar incompatibility)

### ISSUE THREAD

**Issue by Eogen** [Cazsius/Spice-of-Life-Carrot-Edition#16]
When using a mod like 'multihotbar' that changes the position of the 'hearts row', the text display which is put next to the 'heart row' does not find the new position -- it appears to be locked at a 'distance from bottom' rather than placed relative to the position of the hearts.

**Comment by juliand665** [comment]
This isn't actually an issue with SoL: Carrot, since we don't do any drawing above the hotbar, only increase max health. The incompatibility is between Multi-Hotbar and whatever mod adds that multiplier text.
