### ISSUE TITLE
what should i do in this situation

### ISSUE THREAD

**Issue by VaporeonScripts** [Cazsius/Spice-of-Life-Carrot-Edition#161]
the max is 10 hearts, but i got 2500+ foods to eat, whats the purpose of the mod after that? :sob:

**Comment by VaporeonScripts** [comment]
made this, should be balanced:
![image](https://github.com/user-attachments/assets/1eb9119e-89bc-4b66-bbc4-1825ef701d3e)

**Comment by juliand665** [comment]
lol that's a ton of extra hearts! you might consider increasing costs the further you get, like every 10 from 0-100, every 20 from 100-300, etc.

**Comment by VaporeonScripts** [comment]
i got l2 hostility mod, which will give some troubles, xd , like a lvl 90 warden can have 3000hp, levels can go up over 1000 ,  soooooooooo,seems balanced to me,counting all the charms, accessories and magic stuff

**Comment by juliand665** [comment]
fair enough!
