### ISSUE TITLE
decimals not working+doesnt give hearts

### ISSUE THREAD

**Issue by VaporeonScripts** [Cazsius/Spice-of-Life-Carrot-Edition#162]
![image](https://github.com/user-attachments/assets/30aa1df1-0b8b-443c-88b0-f89ec562db24)

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/ae38b261-9034-4695-ac04-03d5a8f91cb9)

**Comment by Mrbysco** [comment]
0.5 is not a valid heart count. It's 1 per health. 2 = 1 full heart

**Comment by juliand665** [comment]
Unless this was changed in the port, we multiply the config value by 2 to only deal with whole hearts. Could totally change that, but we'd have to find a backwards-compatible way. See #56 for some background.

**Comment by Mrbysco** [comment]
There shouldn't have been changes in the port, I might've been mistaken

**Comment by Mrbysco** [comment]
Decimals are invalid in the config though since it expects an integer
