### ISSUE TITLE
crash when opening the book(neoforge 1.21.1 .83)

### ISSUE THREAD

**Issue by VaporeonScripts** [Cazsius/Spice-of-Life-Carrot-Edition#165]
https://mclo.gs/QM5nDKS
![image](https://github.com/user-attachments/assets/71e9368b-5239-4fa2-8c66-95bec634ede5)

**Comment by VaporeonScripts** [comment]
singleplayer

**Comment by Mrbysco** [comment]
A new version that fixes this issue has been released and is awaiting approval

**Comment by Mrbysco** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition/files/5953641
