### ISSUE TITLE
Recent Foods Option like in SoL Stick Edition

### ISSUE THREAD

**Issue by ghost** [Cazsius/Spice-of-Life-Carrot-Edition#18]
I'd like to suggest the option to keep track of recent foods, like the original SoL did, and reward variety based on that. In other words reward a consistent varied diet.

Bonus Points: Let both modes work at once. Permanent bonus hearts for sampling many foods and temporary bonus hearts that only last when you eat a varied diet. Throw in original SoL with this and food could become it's own ever-flexible mod:  Eat the same thing over and over, poor nutrition and no bonus hearts. Eat some variety, good nutrition and no bonus hearts. Eat lots of variety, good nutrition and some bonus hearts. Go out of your way to sample many foods for a permanent bonus!

**Comment by Cazsius** [comment]
This is possible, could branch the mod out to be semi-modular, so you can enable/disable what you want,
Ex: If you want temporary turn that on, if you don't want permanent turn that off

**Comment by juliand665** [comment]
Closing because the whole idea of carrot edition is that you never "lose" progress.
