### ISSUE TITLE
No magama from lava

### ISSUE THREAD

**Issue by j777kin** [Cazsius/Spice-of-Life-Carrot-Edition#19]
Version 2.8.1.1 
The Integrated Dynamics Mechanical drying basin is only producing a magma block the first time it is given lava, each time I load my game.  Subsequent lava goes through the drying animation, but does not produce the magma block.  Reloading the game will give one magma block for the first lava bucket used only.

**Comment by talonos2** [comment]
Are you sure you posted this in the correct GitHub? This mod is about eating food.

**Comment by Cazsius** [comment]
Not an issue for SOL:Carrot. Closing.
