### ISSUE TITLE
Suggestion: Carrots and Sticks.

### ISSUE THREAD

**Issue by darkshadow543** [Cazsius/Spice-of-Life-Carrot-Edition#2]
I feel like this could easily be abused. Instead, why do you not make it so they get a health boost when they eat diversly, but, if they start to eat the same thing over and over, you can drop it off.  Lets say the user has eaten all the foods, then just rely's on PB&Js for food for the rest of game.  It defeats the purpose, why don't you check what they player has eaten for the last 12 or so meals and then based on its diversity, give the boost to the player.  It's still a carrot compared to the original spice of life.

**Comment by talonos2** [comment]
Whether or not it is "abuse" depends entirely on your design intent.

The way the mod acts currently, it sends players on a side quest to try everything at least once, and provides a reward for completing the side quest. After completing it, players choose to ignore it entirely. This is fine.

The way you propose, the mod would require players to carefully micromanage their diet and make food  consumption into large and complex system. This is also fine, has a vastly different design intent behind it.

To be fair, I [originally envisioned](https://docs.google.com/document/d/17uDgCyC5EetRxGQPHtQTZqRAria4Db7ZYMHVWdj-a6c/edit?usp=sharing) the mod being a lot like you described, but I was worried I didn't have enough experience with forge to pull it off, so I scaled it back. Hopefully one day when I have more experience, I'll be able to pull it off, and the current paradigm can be an optional "Gourmand" mode.

**Comment by raindropworks** [comment]
For what it's worth, I'm using both SOL and SOL Carrot Edition on the same server to simulate this.  You can get the health bonus from eating the variety, but if you start eating the same thing over and over you still get the diminishing returns
