### ISSUE TITLE
Food Journal

### ISSUE THREAD

**Issue by lrwerewolf** [Cazsius/Spice-of-Life-Carrot-Edition#22]
It would be nice to have a book that pulls in all food items (perhaps check if the item is edible, or has hunger/saturation value, however) and presents a list of those items, along with a mark if the food's been eaten or not.  I know that the text "Not yet eaten!  What does it taste like?" gets added, but trying to search for this with "#yet" (JEI's flag for tooltip search, for the word 'yet') doesn't return results.  If such a book had an option to filter between foods eaten, foods not eaten, all foods, this would be even better.

It gets quite tedious after a few hundred different foods to manually search through JEI for foods one has not yet eaten to make more progress in getting more hearts.

**Comment by juliand665** [comment]
This will be part of the next update! Implemented in 04dc6de

**Comment by lrwerewolf** [comment]
Awesome news!  Thanks!  :)

**Comment by juliand665** [comment]
[The new update just got approved on CurseForge!](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition/files/2686895)

Feel free to reopen this issue if you feel it's not yet adequately resolved :)
