### ISSUE TITLE
Food reset after server upgrade, can I set food back or add hearts or restore from backup ???

### ISSUE THREAD

**Issue by mcdodge34** [Cazsius/Spice-of-Life-Carrot-Edition#26]
Ok, following a simple server upgrade, I seem to have lost all my progress in your mod, is there any tricks to set it back, I'm OP on my server but have no idea how I would set it back to where I was or which file I need to restore from a backup to get my stats back, any help would be appreciated.

**Comment by SumaniPardia** [comment]
It looks like they changed the NBT in the player.dat file so they either need to push a fix for converting old tags or you need to edit every entry yourself to add the number at the end...
![phcreset](https://user-images.githubusercontent.com/38802058/39391481-987bc1fa-4a69-11e8-8c29-e734c2474d1c.PNG)

**Comment by mcdodge34** [comment]
Ouch, I hope for a fix, now I know what went wrong, I'll keep a copy of the old player.dat ready if a fix is possible

**Comment by SumaniPardia** [comment]
Be sure to update the level.dat > Player folder as well if you're playing single-player.

**Comment by mcdodge34** [comment]
Nope, on server, wouldn't work, I think I'm just gonna give up on the benefits of this mod if there's no easy fix possible, its a nice idea, but if the data keeps getting corrupted after updates of server and we can't get it back to where it was, its not worth it.

**Comment by SumaniPardia** [comment]
This should be a one time process as the NBT was updated to add the meta tag for the food.  Unless the developer changes the format again it should stick.

**Comment by Cazsius** [comment]
Issue seems to be solved.
