### ISSUE TITLE
Actually Addition's coffee is cheating

### ISSUE THREAD

**Issue by tipeon** [Cazsius/Spice-of-Life-Carrot-Edition#28]
I found some weird behavior with Actually Addition's coffee.

Using modpack Modern Skyblock 3, version 3.3.1.4 (which uses SOL:carrot 1.12.1-1.3)
I drank a coffee with no modifiers, and it was marked "eaten".

Then I brewed myself a speed + fire resistance coffee:
- it was "not yet eaten". (so far, so good)
- it stayed "not yet eaten" even after I drank it ... multiple times.
- the /sizefoodlist was incremented multiple times.

I did not push the tests too much, because it is my main game (and it is 1 am). I may do some more tests tomorrow.

**Comment by Cazsius** [comment]
This is interesting, will have to investigate

**Comment by juliand665** [comment]
[The new update just got approved on CurseForge!](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition/files/2686895)

Feel free to reopen this issue if you feel it's not yet adequately resolved :)
