### ISSUE TITLE
A crash occurs when joining a world in which you've eaten food from a now removed mod

### ISSUE THREAD

**Issue by TheLimePixel** [Cazsius/Spice-of-Life-Carrot-Edition#29]
https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/543

**Comment by ghost** [comment]
https://screen.ilikepudding.de/i7h48t80a2.png

**Comment by juliand665** [comment]
oops, accidentally fixed this for 1.11.2 rather than 1.12.2
reopening…

**Comment by juliand665** [comment]
welp, seems the commit didn't auto-close it, but yeah, it should be fixed in 1.3.2, coming very soon!

**Comment by Username2-stack** [comment]
[crash-2020-05-20_16.14.34-server copy.txt](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/4671792/crash-2020-05-20_16.14.34-server.copy.txt)
This issue seems to happen in the 1.14 version as well.

**Comment by juliand665** [comment]
Tracking in #94 now.
