### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by abloodyfetus** [Cazsius/Spice-of-Life-Carrot-Edition#3]
https://pastebin.com/pyFecUAW
I just cant seem to get it to work "/

**Comment by Cazsius** [comment]
I'm looking into this now.

**Comment by talonos2** [comment]
Question: Is this running on a dedicated server?

It's saying it can't find the "EntityPlayerSP", which is really odd. Sorry about this, it's the first time I tried messing with packets.

**Comment by Cazsius** [comment]
@talonos2 Yes it is on a server, see line 105.

**Comment by talonos2** [comment]
Welp, that'll be it. I guess some classes just plain don't exist on a server.

Could you look into it? I'm at work right now and will be for hours yet. Maybe a few "world.isRemote" checks? Just make sure that when connecting to an external dedicated server that the tooltips still work.

Also, I guess we gotta start doing and testing server builds now. :(

**Comment by abloodyfetus** [comment]
its crashing during pre-init I guess?

**Comment by Cazsius** [comment]
Correct, we'll look into it. I can't quite today but hopefully a hotfix will go out soon.

**Comment by abloodyfetus** [comment]
no rush! I appreciate the quick response

**Comment by squeek502** [comment]
One way to solve this is create a helper class like so for use in packet handling: https://github.com/squeek502/SpiceOfLife/blob/1.9.4/java/squeek/spiceoflife/network/NetworkHelper.java

**Comment by Cazsius** [comment]
Fixed and released:
https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition/files
