### ISSUE TITLE
Please do not use localization as a translation of singular or plural form.

### ISSUE THREAD

**Issue by Snownee** [Cazsius/Spice-of-Life-Carrot-Edition#31]
You should add a new entry instead.

https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/blob/97eed3fbb2433bd375a4235ca7bd7c46f4a0dde1/src/main/java/com/cazsius/solcarrot/command/CommandSizeFoodArray.java#L57

https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/blob/97eed3fbb2433bd375a4235ca7bd7c46f4a0dde1/src/main/java/com/cazsius/solcarrot/command/CommandSizeFoodArray.java#L61

**Comment by Cazsius** [comment]
If you want, feel free to make a PR and I will review and accept it.

**Comment by juliand665** [comment]
This should be fixed in the latest version (1.3.3); check curseforge later for updates!
