### ISSUE TITLE
API to tell mod about adhoc composite foods

### ISSUE THREAD

**Issue by Wabbit0101** [Cazsius/Spice-of-Life-Carrot-Edition#34]
**Request:** A way (api callback or capability) to tell solcarrot about foods that represent an adhoc composition of other foods.

**Example:** assume my mod has a sandwich maker...the player can put any combination of a set of items for which solcarrot can determine the static food item values (ItemFood or customized IEdible), but there isn't a way for me at game time to tell the mod "hey, this particular Itemstack of 'sandwichItem' contains a potato bread, steak, fried onions, and a roasted carrot" (There is no useful preconfigured food stat for 'sandwichItem' as it's technically "empty" of value until the player makes a particular one.) With IEdible I can tell you the merged values but not that there are several items there.

**Comment by juliand665** [comment]
Late reply, but how exactly would you want this to work? Would you want eating the sandwich to count as eating all of its components, or should every possible sandwich count as something new?

**Comment by juliand665** [comment]
Closing because we're blocked; feel free to reopen if you decide to specify further :)
