### ISSUE TITLE
Maximum hearts?

### ISSUE THREAD

**Issue by Winddbourne** [Cazsius/Spice-of-Life-Carrot-Edition#36]
I'm looking at the configs and inferring that thirty hearts is the maximum that the mod can add. Is that true?

The pack I'm working on has pam's which adds 660+ foods,  animania (50 foods), the zoo mod (at least twenty) . . . So I'm estimating that for the players to have to work for every heart I need to scale things so at the top end they have eaten at least 700 foods. 

I'm starting them with three hearts, and figure I'll raise how much they need each time they reach a certain milestone . . . At thirty hearts I'd need them to eat roughly 25 foods per heart. 

That wouldn't be so bad if I could raise things by a half heart at a time to motivate people but that doesn't seem to be an option so I'm left wondering if anyone is going to bother trying to each 100 new foods just to get one measly heart or some other ridiculous number. lol

Hopefully I"m misreading and there is no limit. That could be the case as there IS an option to gain 30 hearts at a time listed too. ::crosses fingers::

**Comment by Cazsius** [comment]
There shouldn't be any hard set heart limit, the only limit we start at is 30 for starting hearts. If you add more than that through milestones, you should be all set.

**Comment by Winddbourne** [comment]
Thanks!
