### ISSUE TITLE
Suggestion: Messages

### ISSUE THREAD

**Issue by theshadowake** [Cazsius/Spice-of-Life-Carrot-Edition#37]
Would it be possible to make the messages shown in the center of the screen stay longer? They disappear so fast it is hard to read them (I know you can send them to chat instead, but that doesn't look as nice). Maybe a config option for ticks to appear for?

**Comment by juliand665** [comment]
There's a config option to display them in chat rather than in the center of the screen, if that helps :)

**Comment by theshadowake** [comment]
Yep, mentioned that in my post ;) That's how I have it set ATM.

**Comment by juliand665** [comment]
Oh whoops, reading is hard.

**Comment by juliand665** [comment]
All right, I looked around a bit, and it seems like we couldn't easily do this with the facilities minecraft provides (unless we went into reflection territories, but 'ere be dragons), so I'd have to say that's a no, but @Cazsius has the final say on the matter.

**Comment by Cazsius** [comment]
I don't believe this is realistically do-able as this feature is not something I create myself, rather it is already there for use in Forge. Sadly, I don't think we will be able to do this.
