### ISSUE TITLE
Milestone notifications ignore server config

### ISSUE THREAD

**Issue by Fenrirthviti** [Cazsius/Spice-of-Life-Carrot-Edition#38]
When using SOLCarrot on a server, the notifications for milestones appear to use the client-side configuration, rather than the server. This means that if there is a desync (such as a server admin updating the milestones settings) in the server/client configuration, it leads to confusion with players.

Repro steps:

Install SOLCarrot on a server
Adjust the config for milestones to something outside default (such as changing hearts per milestone from 2 to 1, as an easy example)
Connect to the server, eat a few food, observe that the notifications will follow the client's config, not the server.

**Comment by Fenrirthviti** [comment]
Any updates on this? Happy to do any testing on my end if needed.

**Comment by sekelsta** [comment]
Number of hearts shown also seems to follow client config.

**Comment by Fenrirthviti** [comment]
Correct, as stated in my original report.

**Comment by juliand665** [comment]
Actually reopening this until we release. Feel free to test this once the next version is out; I'll close this issue then.

**Comment by Fenrirthviti** [comment]
Thanks! I am not longer using this mod in my current server, but I am more than happy to test to help out. Will report back when I can.

**Comment by juliand665** [comment]
[The new update just got approved on CurseForge!](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition/files/2686895)

Feel free to reopen this issue if you feel it's not yet adequately resolved :)

**Comment by Fenrirthviti** [comment]
Nope, I did a chance to test I just had not reported back yet. It solves the problem for me.

**Comment by juliand665** [comment]
That's good to hear! Thanks for confirming.
