### ISSUE TITLE
Config option for Minimum Hunger needed in order for foods to assist in adding health.

### ISSUE THREAD

**Issue by SonicX8000** [Cazsius/Spice-of-Life-Carrot-Edition#40]
Quoting my comment on Curseforge after someone suggested that I put it here...

-----

*A config option for the minimum amount of hunger needed to be restored in order for X food to assist in adding hearts. One reason is that there's a mod called Pam's HarvestCraft which adds in a bunch of food items and also alters some Vanilla Minecraft food to restore less hunger. Most raw foods that the mod adds restores 1 Hunger aka 1/2 a Drumstick but there are foods that restore more hunger if you make them into a meal, like Pumpkin Bread that restores 5 Hunger aka 2 1/2 Drumsticks.*

 *Say for example the minimum hunger restore needed is 4 Hunger aka 2 Drumsticks and you eat... say Grilled Cheese which restores 8 Hunger Points aka 4 Drumsticks. It'll tick off with "Eaten: Assisted in adding hearts" as usual but... if you eat... say Ice Cream which restores 3 Hunger aka 1 1/2 Drumsticks... it'll tick off as eaten but because it was below the minimum hunger value it could say something like "Eaten: No noticeable effect" or some other message.*

 *This could pretty much set up a challenge where the player would need to prepare proper meals if they wish to gain extra hearts as just eating raw foods wouldn't help you in gaining extra health.*

 *You could also change it to Saturation instead of Hunger, if you wish via the config. The same rule will apply but instead of minimum Hunger it'll be minimum Saturation in order for foods to assist in adding hearts or both Hunger & Saturation if players want to go with that.*

-----

Just kinda feels like the way to gain hearts without chowing down on foods that restores 1 hunger point or so in order to increase your health.

**Comment by TimGoll** [comment]
I second this. I'd really like this especially if played in combination with Pam's and HungerOverhaul. It should be a really small change

**Comment by TimGoll** [comment]
okay, I digged a bit through the code and I think you only have to change this function: https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/blob/master-1.12.1/src/main/java/com/cazsius/solcarrot/capability/FoodCapability.java#L24

@Cazsius if you don't have the time to implement this, I could try it by myself and open a PR

**Comment by talonos2** [comment]
I like this idea. If Caz doesn't respond, feel free to send that PR anyway and _I'll_ accept it, once [IGMC 2018](https://itch.io/jam/igmc2018) is over and I have time to test it. Until then, I'm busy with other game dev work. ;)

**Comment by TimGoll** [comment]
I think I can do this this weekend. But no promise :D

**Comment by Cazsius** [comment]
@TimGoll Feel free to implement this, and PR it and I will accept it once tested.
Also please feel free to join my discord @ https://discord.gg/JTgMwSW
Or add me @ Cazsius#2026 and we can talk more if you are interested in being more in tune with the development as I have been too busy to code lately.

**Comment by TimGoll** [comment]
Actually I'm the guy who posted the link in your discord:D
If I have the time on this weekend I'll try to do this

**Comment by SonicX8000** [comment]
Just curious of how this suggestion is doing. Not trying to rush.

**Comment by Meshinator69** [comment]
I would love to see this too!

**Comment by Dimentive** [comment]
I’d love to have this as well! 👍

**Comment by juliand665** [comment]
If everything goes well, this will be in the next update!

**Comment by Dimentive** [comment]
Awesome! 👍

**Comment by SonicX8000** [comment]
Aye, nice.

Quick question, will the food book still keep tabs on the food eaten? I was thinking maybe another counter that shows how much food is available that will assist in adding hearts.

Say for example there's 1000 food but only 677 of the food will assist in adding hearts since it's above the minimum hunger/saturation. There will still be a counter for all the food that can be eaten but there's a secondary counter for what foods are available to assist in adding hearts although you won't know what foods will assist in adding hearts unless you taste them.

Could be something like this? Hope I got this right...

-----

Overview
0............10
|--------| 1000
.....|
....3

3/1000
Foods Tasted

2/677
Hearty Foods

0/50
Hearts

-----

I figure 'Hearty' could be a name to use since you gain Hearts for tasting foods in a way.

**Comment by juliand665** [comment]
> I was thinking maybe another counter that shows how much food is available that will assist in adding hearts.

The first page already displays a ton of information; that would be a candidate for a second stat page, if we decide to add that. Or maybe it could be displayed in the tooltips somewhere?

**Comment by TimGoll** [comment]
Building on top of your idea: what about a item, a carot-o-meter, that displays all the information of the items. It should be very userfriendly. Like a menu to cycle through the food. Or something chisel like. 
I could make all textures for the UI and the item this week

**Comment by juliand665** [comment]
> what about a item, a carot-o-meter, that displays all the information of the items. It should be very userfriendly. Like a menu to cycle through the food. Or something chisel like.

Not sure what you mean by that… something like the food book, except that it displays even more information for each item?

**Comment by TimGoll** [comment]
basically, yes.

**Comment by juliand665** [comment]
I feel like it would be most natural to get that information into the food book somehow, maybe by clicking an item you get more info? We could also have additional pages for the foods that aren't valuable enough to count.

**Comment by TimGoll** [comment]
your idea sounds good.
If UI textures are needed I'm able to make them

**Comment by juliand665** [comment]
All right, I'll contact you if necessary :)

**Comment by juliand665** [comment]
[Here's a preview build](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/3105576/solcarrot-1.12.2-1.7.jar.zip) of the next version; feel free to test it and give feedback!

**Comment by SonicX8000** [comment]
![](https://cdn.discordapp.com/attachments/377171551155650560/571403605781905418/solpreview.PNG)

Boring Foods eh? Also... I kinda got confused with the 'Nourishing Foods' as I thought I've eaten 760/1569. Perhaps 'Foods Tasted' could be put there instead while on the first page it'll list your overall total food that you've eaten. Here's a mock-up suggestion as well as some info about it.

-----

![](https://cdn.discordapp.com/attachments/377171551155650560/571407633425104896/solcarrotsuggestion.PNG)

*PAGE 1*

Milestone:
I figure showing the last milestone value could work instead of showing the Nourishing Foods Total.

Foods Tasted:
Shows the overall foods you've eaten instead of just the Nourishing ones. This counter adds both Nourishing & Boring Foods together.

Hearts gained:
Didn't notice anything odd with this so left it alone.

*PAGE 2*

Minimum Food Value:
Left alone as this is alright.

Nourishing Foods:
Basically a counter of how many foods you've eaten that were Nourishing as well as how many are there in total. Also I changed the carrot icon to a Golden Carrot just to have some difference between the carrot textures but it could be still be the normal one if you wish.

Boring Foods:
Pretty much similar to the one being used... only I removed 'tasted' to keep in line with 'Nourishing Foods'.

Hidden Foods:
Left alone as this is alright but I sorta have an idea with this.

While I could've used 'tasted' for both... I don't think it would fit the formatting for the 'Nourishing Foods' hence why I removed it, but that's perhaps just me.

***Hidden Foods - Idea***
Now the idea for Hidden Foods... is that if you hide food, they will have no effect as well as not appearing in the book, like a 'Blacklist' of some sorts. This counter adds up letting you know how many foods are 'hidden' and aren't detected by the Foods Tasted, Nourishing Foods & Boring Foods counters. For example...

Foods Tasted: 0/100
Nourishing Foods: 0/70
Boring Foods: 0/30
Hidden Foods: 0

To...

Foods Tasted: 0/95
Nourishing Foods: 0/68
Boring Foods: 0/27
Hidden Foods: 5
*2 Nourishing, 3 Boring.*

There could be a config option to show the hidden foods just in case one wants to ensure that they added in that food correctly in order for it to become 'hidden'.

*EDIT*
The tooltip says that it subtracts from the total counter already but unsure if that also effects Nourishing & Boring. Perhaps not since it only hides the food but you can gain the effects.

**Comment by SonicX8000** [comment]
I forgot to put this in the previous post.

![](https://cdn.discordapp.com/attachments/377171551155650560/574064012833193984/solcurrenttooltip.PNG)
I kinda think maybe there could be a config option to hide the "This food is not nourishing enough to improve your health" if you haven't yet tasted it and have it show "What does it taste like?". It's perhaps just me on this though.

Also a small suggestion, perhaps colored Tooltips for nourishing/ non-nourishing foods after you've eaten them just to tell them apart.

If eaten and it was nourishing... the Tooltip reads...
![](https://cdn.discordapp.com/attachments/377171551155650560/574072262970572804/solnourishingtooltip.PNG)
...with perhaps the text: "*This food was nourishing enough to improve your health.*" under it.

If eaten and the food wasn't nourishing... the Tooltip reads...
![](https://cdn.discordapp.com/attachments/377171551155650560/574073818465959948/solboringtooltipx.PNG)
...with perhaps the text: "*This food is not nourishing enough to improve your health.*" under it.

Could be a config option for this if one doesn't like the colors. Just keeping it in line with the...

*Not yet eaten!*
*What does it taste like?*

...colored Tooltip for the non-eaten foods.

**Comment by juliand665** [comment]
Hey, sorry this took so long; I was super busy with real-life stuff. Thanks a lot for the detailed feedback! You've certainly provided some interesting alternatives. As to the specifics:

- The whole idea of boring/non-nourishing foods is that they don't matter, so I don't like the idea of putting them on the first page, because then people will be more tempted to collect them all, which would be very annoying with e.g. Pam's. While this does mean some information duplication from the graph above, I feel like it's ultimately the right choice.
- I admit it's kind of confusing to say "`total nourishing foods`/`total foods` nourishing foods", immediately followed by "`eaten boring foods`/`total boring foods` boring foods tasted", even if the "tasted" should make the distinction clear… However, without applying your suggestion for the first page, restating "foods tasted" from there _again_ wouldn't make sense either. Instead, I think the right option would be to just remove the entry for nourishing foods altogether, leaving only "minimum food value" and "boring foods tasted".
- I will probably making hidden foods an actual blacklist (synced from the server), so that's bound to change.
- I'll see if I can improve the tooltips for boring foods, but I definitely want to display to the user that they won't gain anything from them before they even try to craft or eat it.
- The tooltip colors are a great idea; I'll definitely look into that.

**Comment by juliand665** [comment]
This is part of the [newest update, 1.7](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition/files)—please test and provide feedback if you like :)

**Comment by SonicX8000** [comment]
I looked at the book in that version and it's better than want I did in the mock-up image. First page showing the important foods you've eaten while the second page shows the miscellaneous stuff.

The food tooltip was just a config option to hide that bit of info just to give it a bit of a "Is it tasty? Or not-so-tasty?" element to it. Like trying new foods & such and whether or not you like them.... only in MC's world "Will it improve my health or not?" But I do get where you're coming from for that.

Nice to see the colored tooltips making it in. I wasn't sure of the colors to use so I went with those in the images above but the Dark Green/Red makes sense for the Teal coloring.

The Blacklist is nice to have since some foods are 'instant-eat' which doesn't apparently count towards Nourishing/Boring foods. Aether Legacy's Gummy Swets fall under this where I 'instant-eat' it but it doesn't add to the food counter. Unsure if it's a bug on their side or instant-eat foods aren't being counted or something.

**Comment by juliand665** [comment]
Yeah, it was important to me to not "trick" people into expending effort to try foods that wouldn't contribute to their health anyway, which is why I made the tooltips always tell you when a food wouldn't help. A config option to hide that information _might_ be interesting if enough people request it.

As for those instant-eat foods, it's possible they just don't work like other food items because they had to change the way you eat them. They'd either have to tell AppleCore that they're food, or wait for 1.13/1.14, which should make foods more customizable in a sense.
