### ISSUE TITLE
Sandwiches from Culinary Construct aren't detected as food

### ISSUE THREAD

**Issue by WenXin20** [Cazsius/Spice-of-Life-Carrot-Edition#43]
Forge 14.23.5.2796-1.12.2
Carrot Edition v1.3.3
[Culinary Construct](https://minecraft.curseforge.com/projects/culinary-construct) v1.3.0

Sandwiches created by Sandwhich Station block don't seem to be counted as food by this mod or count towards the unique food eaten.

**Comment by Cazsius** [comment]
This has to do with the way Culinary Construct handles food. You'd be better off reporting this on their issue tracker, if they have questions, I can talk with them, my discord is Cazsius#2026
