### ISSUE TITLE
Server crash on 1.3.4

### ISSUE THREAD

**Issue by CritFlaw** [Cazsius/Spice-of-Life-Carrot-Edition#46]
Version 1.3.4 has a server-side crash. I'm told it's caused by
java.lang.RuntimeException: Attempted to load class blk for invalid side SERVER

https://gist.github.com/CritFlaw/6e8180fc5a28816dce2ded9ffb6735c9

**Comment by juliand665** [comment]
Fixed in dev; see also #45.

Update coming soon!
