### ISSUE TITLE
Server-side crash with latest version 1.12.2

### ISSUE THREAD

**Issue by xAlicatt** [Cazsius/Spice-of-Life-Carrot-Edition#47]
Crash report: https://paste.dimdev.org/iwaxugiwah.rb

Don't know if it's actually your mod or FTB Utils causing this (both are in the error), but rolling your mod back to the previous version makes the crash not happen.

**Comment by juliand665** [comment]
Sorry about that. This should be fixed in the next version, coming soon. Will close then.

**Comment by juliand665** [comment]
https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition/files/2682845
new build is up! sorry it took so long :)
