### ISSUE TITLE
[Question] Commands

### ISSUE THREAD

**Issue by NielsPilgaard** [Cazsius/Spice-of-Life-Carrot-Edition#49]
Hey o/

Are the commands `/foodlist size` and `/foodlist sync` meant to be OP only?

**Comment by juliand665** [comment]
`/foodlist size` isn't, but now that we have the food book, we're probably going to make all `/foodlist` subcommands be op-only and take a player as argument, since they should only be necessary for administrative stuff.

**Comment by juliand665** [comment]
By the way, the food book will be even nicer in the next update! \o/

**Comment by Dimentive** [comment]
The food book is great. I’m excited about the update where you’ll make the book show your progress to the next milestone, though, as that would be very useful! 👍

**Comment by NielsPilgaard** [comment]
Thanks for the quick response as always :)
