### ISSUE TITLE
Option to view diffrent metadata as different items?

### ISSUE THREAD

**Issue by kyeiti** [Cazsius/Spice-of-Life-Carrot-Edition#5]
I'm playing with [Terraqueous](https://minecraft.curseforge.com/projects/terraqueous?gameCategorySlug=mc-mods&projectID=244870), but once I eat one fruit from the mod all other fruit from the mod are marked as eaten as well. I assume this is the case because the fruits use the same base item and only differentiate in the metadata. Would it be possible to recognize them as individual food items?

**Comment by Cazsius** [comment]
This is planned for the future to be fixed, metadata is the case, this also happens with the 2 vanilla golden apples.
