### ISSUE TITLE
Rework Commands

### ISSUE THREAD

**Issue by juliand665** [Cazsius/Spice-of-Life-Carrot-Edition#50]
Now that we have the food book, most players shouldn't really need to use commands anymore, so we may as well focus entirely on the admin side, make them op-exclusive, and take a player as argument. That way, admins have full control over people's progress, both read and write.

**Comment by Winddbourne** [comment]
I was just going to create a bug report for this . . . 

I'm working on a pack where I need to use Better Questing to OP reset the player's food list and health when they die.  But I was having trouble figuring out the right syntax to tell the computer what player to clear.

"/foodlist clear @p" wasn't working and having the quest book run the command without it gave me an error saying I had to specify which player to target.  I was going to report it as a huge bug. I actually never even considered that a player would be running the command. 

I use it for testing . . . but no player on a server using my pack is going to have OP capacity. If they wanted to restart for some reason they would need to have an admin with OP clearance use the command on them . . . the same way I was having to use the Better Questing mod with OP clearance to run the command whenever a player died. 

Of course, if there also was an option in configs to lower or reset the player's health on death by default that would be amazing too. :)

**Comment by juliand665** [comment]
As a workaround, you should just be able to use `/execute` for now. I'm not sure of the exact syntax in 1.12, but something like `/execute @p ~ ~ ~ /foodlist clear` should work.

**Comment by juliand665** [comment]
Remembering when a food was last eaten and removing the `n` longest-uneaten foods upon death would certainly be interesting though!

**Comment by Winddbourne** [comment]
That was a good idea, and I tried it... then I laughed and laughed. 

![2019-06-22_02 32 25](https://user-images.githubusercontent.com/24589533/59960450-614dba80-9496-11e9-9329-e7186b9db7a4.png)

![2019-06-22_02 33 04](https://user-images.githubusercontent.com/24589533/59960453-66ab0500-9496-11e9-86ae-8bd06518cc9d.png)

It seems like trying to short cut things this way is exactly the same as having Better Questing do the command with the "via player" option selected. 

If I type in "/foodlist clear" myself the command works . . . but if I use Better Questing or the Execute function to do the same thing it comes back with the error "You must specify which player you wish to perform this action on." 

If I had to guess I think the "via player" option is either using "/execute" itself, or is doing something very similar.

**Comment by juliand665** [comment]
Ah yeah, I found the issue. Will be fixed in the next build, along with just allowing you to specify a player as argument!

**Comment by juliand665** [comment]
If you're feeling up to it, I'd appreciate a quick beta test of [this build](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/3318058/solcarrot-1.12.2-1.8.jar.zip) I just exported; just to make sure I didn't break anything!

**Comment by Winddbourne** [comment]
Sure I'll install it on the pack I'm working on now . . . best case I get to test the play balance on my idea a bit early . . . worst case I send you a crash report. lol

I'm hoping I can use this to make death a bit more painful without making it devastating . . . resetting your hearts to 5 and making you eat to build back up isn't too bad if you have a farm, and unless you want to run in circles forever or constantly damage yourself you aren't going to recover from it super quickly.

**Comment by Winddbourne** [comment]
Ok . . . no crash but something is odd here.


   - changing to the new file reset my spice of life custom configurations
   so I had to redo them


   - I'm still getting the same errors both when I use the "from player"
   option in better questing and when I simply put in "/foodlist clear @p"


[image: 2019-06-23_13.16.22.png]

**Comment by juliand665** [comment]
Looks like the image you included didn't quite work; i guess that's due to the email thing?

It's very strange that it'd reset your config. Is that from 1.7 to 1.8? Because I didn't change anything about the config system…

I explicitly tested with `/foodlist clear @p` (also tried again just now) and that seems to work fine on my end. Perhaps the build broke somehow; I'll give you a new one soon.

**Comment by juliand665** [comment]
How about [this one](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition/files/2728782)?

**Comment by Winddbourne** [comment]
Yup, it's working now. I also figured out the problem with the previous download too and it was user error on my end.

**Comment by juliand665** [comment]
Sounds great! Looks like 1.8.1 is almost ready to go out of beta then :)

**Comment by juliand665** [comment]
All right, this is done in [the latest version](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition/files/2731062)!

**Comment by Winddbourne** [comment]
Great work! I just tested the death reset and it worked perfectly. No more clunky methods of detecting when a player dies, no more finding a way to run a command to reset things . . . all I need to do is set it up and let it run. . . and the best part is how quickly you got it done. 

I know you mod makers don't get your share of appreciation . . . and I'll be the first one to get in contact with a bug or a feature request . . . so I want to make sure to write something positive here. :)

**Comment by juliand665** [comment]
Thank you! I think I speak for all modders when I say that making people happy with what I create is one of the best feelings :)
