### ISSUE TITLE
Issue with Astral Sorcery + Thaumcraft if SoL Carrot Edition present

### ISSUE THREAD

**Issue by Mack1410** [Cazsius/Spice-of-Life-Carrot-Edition#52]
Having both Spice of Life Carrot Edition and Thaumcraft present alongside Astral Sorcery causes the Astral Tome to not be given to the player on world creation. 

Only Thaumcraft and Astral Sorcery together do not cause this issue, neither does it happen if SoL Carrot Edition is replaced with normal SoL, or with only Astral Sorcery and SoL Carrot Edition

**Comment by juliand665** [comment]
Thanks for the report! I was able to reproduce locally, which is the first step towards fixing it :)

Very strange…

**Comment by juliand665** [comment]
All right, after much investigation, I've concluded that this is out of our control and posted a lengthy write-up on Astral Sorcery's issue tracker: https://github.com/HellFirePvP/AstralSorcery/issues/1034. I suggest you go subscribe to that thread :)
