### ISSUE TITLE
[Request] Config blacklist for foods hidden with CraftTweaker

### ISSUE THREAD

**Issue by Dissgruntled** [Cazsius/Spice-of-Life-Carrot-Edition#53]
I noticed that foods that I have hidden with CraftTweaker still show in the books total food count and Foods not eaten list. Would it be feasible to add in a blacklist in the config where I could add these same foods and have the book ignore them, so they no longer appear in the Not eaten list and are not part of the total food count?

Thank you :)

**Comment by juliand665** [comment]
That should be doable! I was just looking into hooking into JEI to automatically hide the same items, but I don't think that's easily possible, so this'll have to do.

**Comment by juliand665** [comment]
Would it be okay if this blacklist was only applied client-side? It's way easier to implement that way ^^

**Comment by Dissgruntled** [comment]
I never play on a server, always single-player. So for me personally, it's fine.

**Comment by juliand665** [comment]
I added the blacklist; [here's a preview build](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/2998848/solcarrot-1.12.2-1.6.3.jar.zip) so you can test and report back if it works as expected :)

**Comment by Dissgruntled** [comment]
Just tested it and it works exactly as I had hoped. Fantastic! Thank You!

**Comment by juliand665** [comment]
Great! @SeanChengN would you like to localize already? The new key is `config.solcarrot.food_blacklist`; just tell me the translation and i'll copy it over, or you can always open a pull request.

**Comment by SeanChengN** [comment]
@juliand665 `config.solcarrot.food_blacklist=隐藏的食物`

**Comment by juliand665** [comment]
@SeanChengN Fast as always! Thanks :)

**Comment by juliand665** [comment]
The update is [out](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition/files/2692785)! Sorry it took so long; I decided to also add the logo to the mcmod.info (so it shows up in your mod list) in the same update, and that was more complicated than expected :p
