### ISSUE TITLE
Show Number of Foods to Next Milestone in Food Book

### ISSUE THREAD

**Issue by Dimentive** [Cazsius/Spice-of-Life-Carrot-Edition#54]
The food book currently shows the previous milestone, the next milestone, and how many unique foods the player has eaten. It’s extremely useful, but I have one small suggestion: to add a number somewhere in the food book that shows the number of unique foods that the player needs to eat to reach the next milestone, just to save the player from doing math.

So, for instance, if the player has eaten 47 unique foods and the next milestone is 60 foods, it would show the number 13 somewhere in the book—for example, somewhere in this red square.

![SoL - Carrot Edition food book suggestion](https://user-images.githubusercontent.com/34230933/55184625-ea549e80-5192-11e9-9b7f-18b7d624c300.png)

**Comment by juliand665** [comment]
First of all, thanks for the clean report!
This would be easy enough to implement, but I personally think these little bits of math mods can make you do to be quite fun and "part of the experience". Will have to evaluate what others think—if more people report this (or 👍 your report or something), I'll definitely reconsider.

**Comment by Dimentive** [comment]
That’s understandable.

I’m suggesting this idea because I’m terrible at math, but it’s not that big of a deal if you choose to leave it out. Nevertheless, I love your mod, by the way! Spice of Life: Carrot Edition actually makes me create a bunch of different foods and experiment with types of foods that I would never have tried hadn’t it been for this mod. It’s so much fun being rewarded with extra hearts than being punished by fewer hunger points. 👍

**Comment by Dimentive** [comment]
I know it’s intended behaviour. It’s a suggestion. 😛

**Comment by juliand665** [comment]
Right. The label is mostly for us devs to see that it's not something we're actively working on :p

**Comment by juliand665** [comment]
:)

**Comment by Dimentive** [comment]
You added it?

**Comment by juliand665** [comment]
yeah, we found a nice place to "hide" it in the end (power user feature): if you hover over the carrot to the left of the graph, it'll show the remaining food count in a tooltip

**Comment by Dimentive** [comment]
Awesome! Thanks. I can’t wait for the update.

**Comment by Dimentive** [comment]
Awesome! Thanks. I can’t wait for the update. ᴵ ʰᵃᵗᵉ ᵐᵃᵗʰ

**Comment by juliand665** [comment]
This is part of the [newest update, 1.7](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition/files)—please test and provide feedback if you like :)
