### ISSUE TITLE
Food Book replaces Vanilla Recipe Book?

### ISSUE THREAD

**Issue by Dissgruntled** [Cazsius/Spice-of-Life-Carrot-Edition#55]
The Patchouli mod has a config option to let any book that utilizes its API to replace the vanilla recipe book in the inventory GUI. I was curious if something like this was possible to do with the food book? Would look like this: https://i.imgur.com/3B3f4D6.jpg

**Comment by juliand665** [comment]
<img width="322" alt="image" src="https://user-images.githubusercontent.com/827762/55488732-e3190f00-5630-11e9-838b-2045d503527a.png">
The Vazgoo has spoken. Short of actually implementing this ourselves (which would be pretty complex), there's no way to do what you suggested.

Interesting idea though! If someone else would like to implement it, we're always open to pull requests.
