### ISSUE TITLE
.5 Heart value option

### ISSUE THREAD

**Issue by Meshinator69** [Cazsius/Spice-of-Life-Carrot-Edition#56]
I wanted to ask about implementing a .5 or half heart value config option. I thought this might be an interesting feature to implement, mostly because the modpack I'm playing with adds 1400+ food items, and I'm really trying to stretch out heart gain and incentivize food variety. I already have it set to one heart (with gradually increasing food amounts), and set custom milestones up to 500 but I'm still flying through those extra hearts! I'd love to hear some thoughts or if this is even possible, thanks in advance!

**Comment by juliand665** [comment]
So I took a look at implementing this and, while the actual implementation would be pretty trivial, results are not ideal. Unfortunately, Minecraft displays max health rounded to the next full heart, so 10.5 hearts max health look like this, making it seem like you're not actually at max:

![Screenshot of health bar with 10.5 hearts max health](https://user-images.githubusercontent.com/827762/55447916-14a8c080-55c6-11e9-93c9-2a8a3848abec.png)

Changing that would require all sorts of trickery, probably resulting in incompatibilities with other mods.

**Comment by juliand665** [comment]
Maybe consider just having more milestones anyway? 1400 foods is a _lot_ of work, so it'd make sense for that to be rewarded with lots of hearts.

**Comment by za3k** [comment]
Well, oh well. Can you clearly document that this doesn't work in the config?
