### ISSUE TITLE
Losing history after dying

### ISSUE THREAD

**Issue by EmosewaGamer** [Cazsius/Spice-of-Life-Carrot-Edition#6]
After you die, all the items that you've eaten seem to be reset. Idk if it's just the tooltips or if the entire eating history is reset.

**Comment by EmosewaGamer** [comment]
After a bit of testing, I realized that both the hearts and food history get reset. Is this intentional?
I should have also mentioned that this is on version 1.12.

**Comment by Cazsius** [comment]
What version of the mod are you using?

**Comment by EmosewaGamer** [comment]
1.1.0 as it's the only 1.12 version.

**Comment by Zeevian** [comment]
Personally can confirm this as well.  Using the same version on 1.12.1 forge 2485

**Comment by Cazsius** [comment]
Fixed https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition/files/2484559

**Comment by usafphoenix** [comment]
i'm losing food history after vising OTG dimensions: flatlands/skylands. (not dying).
