### ISSUE TITLE
There was a problem during loading

### ISSUE THREAD

**Issue by mcmso** [Cazsius/Spice-of-Life-Carrot-Edition#60]
[crash-2019-05-23_20.08.23-client.txt](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/3212072/crash-2019-05-23_20.08.23-client.txt)

**Comment by juliand665** [comment]
This looks like a problem with Harshen Universe United. To be clear, it only crashes when both are installed, but SOLC isn't doing anything wrong here, as far as I know. I'll open an issue on their side :)

**Comment by mcmso** [comment]
> 这看起来像Harshen Universe United的一个问题。需要说明的是，安装时只会崩溃，但据我所知，SOLC在这里没有做错任何事。我会在他们身边开一个问题:)



> This looks like a problem with Harshen Universe United. To be clear, it only crashes when both are installed, but SOLC isn't doing anything wrong here, as far as I know. I'll open an issue on their side :)

Harshen Universe, let me contact you and the author of apple core

**Comment by juliand665** [comment]
I found the thread on Harshen Universe; I'll talk to them there. I don't think apple core needs to be brought into this.

**Comment by mcmso** [comment]
> I found the thread on Harshen Universe; I'll talk to them there. I don't think apple core needs to be brought into this.

I don't quite understand what the problem is, but would it help if you could get in touch with each other

**Comment by mcmso** [comment]
> I found the thread on Harshen Universe; I'll talk to them there. I don't think apple core needs to be brought into this.

Looking forward to your reply
