### ISSUE TITLE
Blacklist Has No Way to Declare Metadata; No Whitelist

### ISSUE THREAD

**Issue by ismschism** [Cazsius/Spice-of-Life-Carrot-Edition#61]
Hi, first of all, great mod! We really like the max health mechanic, and plan to use it alongside the other Spice of Life mod, to give more value to the farmer / foodie players on our small 1.12 server.

We'd like to limit the target foods to a relatively short list (around 75) of pinnacle / hard to find foods, rather than the full set of recipes, which is like 1300+ with Pam's and some other mods installed. 

The problem we've run into is that, unless I'm missing something, the blacklist in the config doesn't work with meta data. So, for example, if you want to include regular Golden Apples as a target food, but not the enchanted version, putting `minecraft:golden_apple:1` into the blacklist doesn't do anything. Both golden apples show up as reward foods in the book. 

This might not be a big deal, if it were only a few vanilla foods we're talking about, but some mods, like Erebus for example, make extensive use of meta data, so you might have 20 foods, named `erebus_foods:0` to `erebus_foods:19`. There's no way to target just some of these items. It seems our only option is to blacklist all of the foods, which is a shame because some of them would be perfect "pinnacle foods" in the mechanic we're going for. 

On a related note (maybe this should be a separate feature request) it would be awesome if there were a white list option in the config. It our case, since we're trying to make a short list items where every food counts, it would be much easier to white list 75 foods than to have to identify and blacklist some 1300.

Thanks!

**Comment by juliand665** [comment]
Those are some good ideas. The metadata suggestion should be pretty easy, and a whitelist sounds doable too. I'll get to it when I find some time :)

**Comment by ismschism** [comment]
Great, thanks! Metadata support would be of particular help in setting up our server. Let's hope it's an easy addition!

**Comment by juliand665** [comment]
This is part of the [newest update, 1.7](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition/files)—please test and provide feedback if you like :)

**Comment by ismschism** [comment]
Wow great, thanks for the quick fix! I'm out of town but will test it next week when I get back.
