### ISSUE TITLE
Blacklist Only Hides Foods

### ISSUE THREAD

**Issue by ismschism** [Cazsius/Spice-of-Life-Carrot-Edition#62]
Hi again, I found another, possibly related issue when trying to blacklist cake (both vanilla and Harvestcraft variants). 

Adding a cake to the blacklist hides it from the uneaten foods section of the book, as expected, but then if you eat from a cake placed in the world, you get the benefit of of it counting toward your max heart total (it shows up in the book) even though the cake item has been blacklisted. 

Note most Harvestcraft cakes have two names registered, e.g. `harvestcraft:carrotcake` and `harvestcraft:carrotcakeitem` (I guess one is the slice version?) and most cakes shows up twice by default in the uneaten foods section of the book. I tried blacklisting both names, but when I tested eating the cake, it still counted toward the food total, despite being blacklisted.

Hope these problems aren't too difficult to fix. We really appreciate this mod! Thanks

**Comment by juliand665** [comment]
The problem isn't the cakes but rather how the blacklist feature currently works. "Blacklist" is a bit of a misnomer; it simply hides the foods on the client (intended primarily for pack makers). A proper blacklist should be server-side, which would require syncing a lot more data than we currently are.

Thus, I was hoping to be able to put this off until 1.13+ forge, which ships with a new config system with config sync built in. In the meantime, perhaps #40 would address this problem in a different way? There's bound to be an official update including that soon.

**Comment by ismschism** [comment]
Yeah, #40 looks like a great option for anyone wanting to quickly limit the mod to high hunger-value foods. That's similar to what we're going for, but we're using more of a handpicked approach, choosing foods that are particularly hard to find, and / or difficult to craft using a wide variety of ingredients. Some of these foods are rare finds, like from BoP or Plants, but wouldn't necessarily qualify as high hunger-value foods.

We spent a bit of time making our custom food list; I think it'd be a fun challenge if we can get it working (mostly just need metadata support from #61). 

I guess we'll just have to add some fancy cakes to the list. It shouldn't be a problem. I mean, who doesn't like cake? :) Maybe we'll make a house rule that you have to throw a party in MC before you can eat it!

**Comment by juliand665** [comment]
Unfortunately, the blacklist currently doesn't stop you from gaining hearts from blacklisted foods, it simply hides them from the food book. I might just bite the bullet and sync the blacklist too, though; that would fix it.

**Comment by ismschism** [comment]
Ah I see... So we would have to disable the recipes entirely in CraftTweaker to prevent the foods from counting? Hmm yeah, I guess we would need a real blacklist to do the pinnacle food mechanic we're going for.

Well, we'd certainly appreciate the functionality if it's not too hard to make it happen! I guess in the meantime, we leave the mod out of our initial server setup and hopefully we can add it in later.

**Comment by juliand665** [comment]
If you add foods to the blacklist later on, that will retroactively apply, so you could always have this mod from the start but in a simpler configuration, if you'd like that. But yeah, I'm afraid the only option would be disabling recipes, and even then, you'd have simple collectible foods like raw meat that would still count unless you also set the minimum food value pretty high.

**Comment by ismschism** [comment]
Okay, thanks for the clarification. We'll probably hold off on installing the mod for now. I'll keep an eye out for updates in the future!

**Comment by juliand665** [comment]
This is part of the [newest update, 1.7](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition/files)—please test and provide feedback if you like :)
