### ISSUE TITLE
[1.14.4] Sidedness issue on dedicated server

### ISSUE THREAD

**Issue by ProsperCraft** [Cazsius/Spice-of-Life-Carrot-Edition#68]
Don't worry 95% of the mods porting have this issue due to sidedness changing in 1.14

Exceprt
https://gist.github.com/ProsperCraft/c879d69c90858bd0ab36325374b991ed

[debug.log](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/3633459/debug.log)
[latest.log](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/3633460/latest.log)
[crash-2019-09-19_15.35.13-server.txt](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/3633461/crash-2019-09-19_15.35.13-server.txt)

**Comment by juliand665** [comment]
Thanks for the report! I addressed this in dc64019.
