### ISSUE TITLE
[1.14.4] Armor bar renders over hearts.

### ISSUE THREAD

**Issue by Gbergz** [Cazsius/Spice-of-Life-Carrot-Edition#69]
Title says it.

The armor bars render over the newly acquired health bar, making it impossible to see those hearts.

Screenshot: [Imgur](https://i.imgur.com/nBI8FH2.png)

You see the first 2 armor bars are a little bit more darker around the edges than the other ones, that's because the hearts are behind them.

**Comment by juliand665** [comment]
Damn, this really sucks. I guess Minecraft or Forge used to handle this automatically, but whatever used to do that doesn't seem to apply to 1.14 anymore.

**Comment by juliand665** [comment]
Actually, this doesn't happen for me on a fresh instance with SoL:C 1.9.1 on forge 28.1.6; it's moving the armor bar just fine.
![screenshot of it working](https://user-images.githubusercontent.com/827762/65373424-b22fa380-dc7d-11e9-83bc-5d5ad7a0760b.png)
Are you using any other mods, and if so, does it still happen without those other mods? Also, which version of forge and SoL:C are you using?

**Comment by Gbergz** [comment]
Huh, hm.. 
Then it has to be some other mod(s) causing it.

Modlist: [Gist.Github](https://gist.github.com/Gbergz/62caf6c4ab3daccf10f34f1e3a80ad34)

Probably too many mods to go through to actually know which one it is..

edit: grammar

**Comment by juliand665** [comment]
Yeah, you can actually cause this issue without SoL: Carrot by eating a golden apple or increasing your health with commands, e.g. `/effect give @s minecraft:health_boost 9999 1`, so we don't really have anything to do with this.

Try disabling the alphabetically first half of your mods and seeing if the issue still happens. If it does, look at the second half and repeat. If it doesn't, put the first half back and disable the second half instead, then repeat with the first half. Eventually, you'll get down to the single mod that causes the issue. Does that make sense?
