### ISSUE TITLE
[1.14.4] Stacktrace in console- unable to log in. java.lang.NullPointerException         at com.cazsius.solcarrot.SOLCarrotConfig.isHearty(SOLCarrotConfig.java:264)

### ISSUE THREAD

**Issue by ProsperCraft** [Cazsius/Spice-of-Life-Carrot-Edition#71]
https://gist.github.com/ProsperCraft/d1f8cca7918217d4d10d72a8c1cfdd79

solcarrot-1.14.4-1.9.2
forge-1.14.4-28.1.40

Modpack- https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by juliand665** [comment]
I'm not entirely sure what's causing this, so I added some more checks which made sense anyway. Can you check if it works with [this build](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/3714271/solcarrot-1.14.4-1.9.3.jar.zip)? (yes, github doesn't let you upload jars, but you can upload zips, lol)

The build should be compatible with clients running 1.9.2; only needs to be updated on the server.

**Comment by juliand665** [comment]
btw just wanted to say I really appreciate what you're doing with all the issue reports from that modpack :)

**Comment by juliand665** [comment]
I'd appreciate if you could retry this with [1.9.3](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition/files/2813746); that should hopefully address this issue and/or a possible underlying cause.

**Comment by juliand665** [comment]
Closing assumed resolved until further notice.
