### ISSUE TITLE
Consistantly getting the wrong amount of hearts!

### ISSUE THREAD

**Issue by Winddbourne** [Cazsius/Spice-of-Life-Carrot-Edition#74]
I'm supposed to gain one heart every so many different types of food the player eats but instead, I'm gaining between 2-4 hearts each milestone.  I literally went from ten health to fourteen in a single jump in my last test after deleting my entire configuration file and reloading from a backup. :(

I'm using solcarrot-1.12.2-1.8.3.Jar.

**Comment by juliand665** [comment]
can you attach your config file?

**Comment by Winddbourne** [comment]
I sure can, and I can give you some background information that might be helpful too.  

I noticed I was getting health too fast in earlier testing and tried to set hearts gained to 0.5 as a fix. That gave me some buggy returns. It gave me half a heart but the tool-tip said it had given me two hearts and the food book said it was giving me just one.  

After that, I set things back to one full heart and started looking more carefully at the numbers using classing bars to really count things more carefully. That is when I realized I was getting 4-8 health at different health increases. 

I then removed classic bars and confirmed it without that mod actually counting the pictures, and then completely wiped my configuration folder and did a test that way using back up configuration files just in case my attempt at going up by half hearts had corrupted something. 

Only after still finding the problem did I decide this was why I'd been gaining hearts too fast all along and send a bug report. Here is a copy of my current config file:

```
# Configuration file

general {
    # If true, trying a new food spawns particles.
    B:"Enable Intermediate Particles"=true

    # If true, reaching a new milestone spawns particles.
    B:"Enable Milestone Particles"=true

    # If true, reaching a new milestone plays a ding sound.
    B:"Enable Milestone Sounds"=true

    # Foods in this list won't affect the player's health nor show up in the food book.
    S:"Food Blacklist" <
        minecraft:rotten_flesh
        primal:fish_cod_rotten
        primal:fish_salmon_rotten
        primal:fish_clown_rotten
        primal:fish_puffer_rotten
        primal:fish_lava_worm_rotten
        primal:fish_lava_crawdad_rotten
        primal:shark_meat_rotten
        primal:gator_meat_rotten
        primal:horse_meat_rotten
        primal:wolf_meat_rotten
        primal:ovis_meat_rotten
        primal:pigman_meat_rotten
        primal:bear_meat_rotten
        primal:llama_meat_rotten
        primal:bat_meat_rotten
     >

    # When this list contains anything, the blacklist is ignored and instead only foods from here count.
    S:"Food Whitelist" <
     >

    # A list of numbers of unique foods you need to eat to unlock each milestone, in ascending order.
    I:"Milestone amounts" <
        2
        2
        4
        4
        4
        4
        6
        6
        6
        6
        6
        6
        8
        8
        8
        8
        8
        8
        8
        8
        10
        10
        10
        10
        10
        10
        10
        10
        10
        10
        15
        15
        15
        15
        15
        15
        15
        15
        15
        15
        15
        15
        15
        15
        15
        20
        20
        20
        20
        20
        20
        20
        20
        20
        20
        20
        20
        20
        20
        20
        20
        20
        20
        20
        20
        48
        48
        48
        48
        48
        48
        48
        48
        48
        48
     >

    # The minimum hunger value foods need to provide in order to count for milestones, in half drumsticks.
    I:"Minimum Food Value"=1

    # Whether or not to reset the food list on death, effectively losing all bonus hearts.
    B:"Reset on Death"=true

    # If true, the food book also lists foods that you haven't eaten, in addition to the ones you have.
    B:"Show Uneaten Foods"=false

    # Number of hearts you start out with.
    I:defaultHeartCount=5

    # Number of hearts you gain for reaching a new milestone.
    I:heartsPerMilestone=1

    # If true, foods indicate in their tooltips whether or not they have been eaten.
    B:isFoodTooltipEnabled=true

    # Whether the messages notifying you of reaching new milestones should be displayed above the hotbar or in chat.
    B:shouldShowProgressAboveHotbar=true
}
```

I hope that helps. :)

**Comment by juliand665** [comment]
Thanks for the report! It looks like you've misunderstood how the milestone amounts work: each number is the total number of foods you need to have eaten to get to that point, not the amount of foods needed to get to the next milestone (hence the default being `5, 10, 15, 20, 25`). So your list should actually start `2, 4, 8, 12, 16, 20, 26, 32, …`.

As for half hearts, [this has actually come up before](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues/56). Basically, a non-integer number of max hearts looks wrong, so we've decided not to implement it. I'm surprised forge didn't complain about you setting the hearts to `0.5`; I would have expected it to throw some errors or reset it or something.

**Comment by Winddbourne** [comment]
AH! Thanks that makes more sense. No wonder I was getting odd results. lol
