### ISSUE TITLE
Config file not appearing in folder

### ISSUE THREAD

**Issue by MuuKnew** [Cazsius/Spice-of-Life-Carrot-Edition#76]
Minecraft version: 1.14.4
Mod version: solcarrot-1.14.4-1.9.3, released onto curseforge Oct 21, 2019
Edit for extra detail:
Forge version: 28.1.107
Configuration file does not show up in a fresh install of minecraft through Twitch's modpacks (personal modpack). There are other config files for other mods present in "\Instances\ABA\config\" (Which is the appropriate folder for this modpack), but none for SoL:CE.

**Comment by MuuKnew** [comment]
I have just now also confirmed that this bug exists with no other mods present in the modpack.

**Comment by juliand665** [comment]
Thanks for reporting this in the right place!

Can you give an example of a mod (preferably open-source) whose config is generated correctly? I'd like to compare to their code to see what I'm doing wrong, haha.

**Comment by MuuKnew** [comment]
Aquaculture 2 seems to, V0.3.0
https://github.com/TeamMetallurgy/Aquaculture/
Curios as well
https://www.curseforge.com/minecraft/mc-mods/curios
Doggy Talents
https://github.com/percivalalb/DoggyTalents/
Edit: clickable URLs didn't seem to work correctly.
If any more are needed, please comment again.

**Comment by juliand665** [comment]
That's helpful, thanks for the research! Nothing obvious popped out at me; I'll be looking into it further soon :)

**Comment by juliand665** [comment]
I've figured out what was causing the issue: I was registering the config too late, so it wasn't generating the client one (which happens on startup). Fix will be in the next update!

**Comment by juliand665** [comment]
Hey! Sorry it took so long; I was having some issues in the dev environment. [Here](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition/files/2874104) is the new version on curseforge.
