### ISSUE TITLE
Consumed Food Data Lost with Immersive Portals

### ISSUE THREAD

**Issue by WenXin20** [Cazsius/Spice-of-Life-Carrot-Edition#78]
Minecraft v1.14.4
Forge v28.1.90
Sol Carrot v1.9.3
Simple Farming v1.2.5

The game froze after the player obtained Cumin Seeds from Simple Farming. The seeds also display a tooltip error when viewed with JEI. No crash report was created.

[Log](https://gist.github.com/WenXin20/b83c7ee4843bbf25e5ab7d8a64386cf2)

**Comment by juliand665** [comment]
Uh oh, looks like the player lost the attached food list data somehow. Could you list the other loaded mods? I doubt simple farming is the actual cause of the issue; it'd probably happen with all foods.

**Comment by WenXin20** [comment]
Then I suspect it may be Immersive Portals. I had just used a portal before this happened. I had also just seen an issue there about player capabilities being lost. The issue is located at qouteall/ImmersivePortalsModForForge#3

**Comment by juliand665** [comment]
Good catch, that's probably it!

**Comment by WenXin20** [comment]
So this would be up to Immersive Portals to fix, correct?

**Comment by juliand665** [comment]
Yeah, especially considering it affects other mods too. My usual reasoning is that if it works with vanilla nether/end portals, it should work with any mod, and if it doesn't, it's that mod's fault, not ours. There's not much we can do about this without looking into exactly how immersive portals does its teleportation.

**Comment by WenXin20** [comment]
Forgot to close this, as far as I can tell, it is fixed by v7 of Immersive Portals. :)

**Comment by juliand665** [comment]
Oh yeah, thanks for the cooperation!
