### ISSUE TITLE
2 hearts lost

### ISSUE THREAD

**Issue by Dimentive** [Cazsius/Spice-of-Life-Carrot-Edition#79]
SoLC: 1.8.3
MC: 1.12.2
Forge: 14.23.5.2847

My friend had 8 gold hearts, but when they died, they had 6. Reset on death is false.

**Comment by juliand665** [comment]
Can you take a look into the food book and share a screenshot of the first page?

**Comment by Dimentive** [comment]
Book said 6 hearts unlocked. Unable to take a screenshot at the moment. Will soon.

**Comment by juliand665** [comment]
All right. Are you sure it said 8 before or was there perhaps something else boosting the health? There's absolutely no conceivable way only part of the food list might be copied over to the respawned player—it's all or nothing.

**Comment by Dimentive** [comment]
Hmm. It might’ve been the [Nutrition](https://github.com/WesCook/Nutrition) mod that gave him eight hearts in total, causing him to think that he lost two hearts when he died. In hindsight, this is almost definitely not an issue with Spice of Life: Carrot Edition—or even an issue at all.

Thanks for helping me realize this. Closing this issue now.
