### ISSUE TITLE
[Incompatibility] Spice of Life: Carrot Edition and First Aid, Eating food kills you

### ISSUE THREAD

**Issue by dreckz** [Cazsius/Spice-of-Life-Carrot-Edition#83]
**MC: 1.15.2
First Aid Version: 1.8.0
SoL:CE Version: 1.9.4**

When attempting to eat food with Spice of Life enabled, it ends up reducing your hp for some reason. Tried using this with hunger strike in conjunction with these two mods, and it severely reduces HP.

**Comment by juliand665** [comment]
Discussing in https://github.com/ichttt/FirstAid/issues/76 for now.
