### ISSUE TITLE
[1.15.2] Stuck on 99% when preparing spawn (loading world AND creating new world)

### ISSUE THREAD

**Issue by Kavrrin** [Cazsius/Spice-of-Life-Carrot-Edition#84]
so i'm trying to make a personal 1.15.2 modpack for singleplayer play and i've been having this issue with quite a few mods. problem is this is the only one that has this issue that i really actually care about (ie actually 100% want in my modpack although i can live w/o it)

so far i've been testing and trimming my load order and removing anything that does this, but essentially, when creating or loading a world, the launcher reaches "Preparing spawn area:" with a percentage somewhere in the 90s and then just ceases all function. screen is stuck on that square graphic with 100%. no more log input. 

i'm not sure if this is an issue with this particular mod, as i'm having this problem with MANY others, but in case this is conflict related, my (currently working) mod list is as follows:

![1](https://user-images.githubusercontent.com/35414606/77859693-e78eee00-71d8-11ea-8c20-0ca9fabdf853.png)
![2](https://user-images.githubusercontent.com/35414606/77859694-e8c01b00-71d8-11ea-8359-56a11e3b06ce.png)

again this might be my fault and if so i'm sorry, but if it's compatibility related, i figured i'd bring it to your attention. thank you for the consideration and the mod

Edit: forge version is 31.1.30

**Comment by juliand665** [comment]
there's a pretty simple way to isolate causes: if you remove this mod, does it still get stuck? if so, it's not our fault, if yes, it might be.

**Comment by Kavrrin** [comment]
sadly yes. once i removed it, the worlds started loading again. ive tried updating my java runtime as a few troubleshooting threads on reddit suggested, but it keeps snagging.

**Comment by juliand665** [comment]
huh, that is weird. so it looks like an incompatibility then, i guess?
the next step would be to remove other mods until it stops breaking (since having just our mod will almost certainly load, but maybe test that too).
the fastest way to do that is to bisect, i.e. remove half of other mods (dependencies will complicate this, but it's still the fastest i think), see if it still breaks. if it does, remove half again, otherwise add back one half of those you removed. i hope that makes sense; i'm just trying to avoid putting together all those mods for testing on my machine :p

**Comment by juliand665** [comment]
alternatively, and a little less complicated, just remove chunks of mods that make sense to you and see when it stops breaking. try to isolate it to as few mods as possible, where removing any one of those will make it all work again.

**Comment by Kavrrin** [comment]
alright good news i finally found the offending mod, which turned out to be Apotheosis. on their issues page they also have a report of this exact error (and have honestly blown it off but thats a story for another time) from a user with a smaller pack but ultimately a lot of the same mods i had.

after some testing and shuffling around jar files, it was absolutely this mod and not yours. this is on THEIR END and i'm so sorry for causing potential worry.

again this is Apotheosis and after removing it i haven't had a single load error

**Comment by juliand665** [comment]
glad to hear that! thanks for putting in the work :)
