### ISSUE TITLE
Opening the Food Book causes it's window to appear to all players.

### ISSUE THREAD

**Issue by Ryahsson** [Cazsius/Spice-of-Life-Carrot-Edition#85]
Quote from Teralitha:
"Found a bug.  Its the food book. If you are in multiplayer, and one person has and uses the book, every player gets the book popped open in their faces even if they don't have the book them selves.  Kind of an issue if someone is in middle of a fight."

**Comment by juliand665** [comment]
This is nigh-impossible for me to test at the moment (simultaneously running a server and two clients is just not something my current computer can really do), but I'm _pretty_ sure I fixed it.

**Comment by juliand665** [comment]
Officially approved on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition/files/2959847).

**Comment by juliand665** [comment]
The fixed version is now approved on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition/files/2959864)
