### ISSUE TITLE
[1.15.2+][suggestion] number of food needed.

### ISSUE THREAD

**Issue by Bass2style** [Cazsius/Spice-of-Life-Carrot-Edition#88]
Hi,

i have installed your mod in my custom pack, besides of Pam's HarvestCraft.
that's a lot of food opportunities. (my pack have 299 food possibilities, with MC's foods, Pam's foods and other third party additions)

i've checked the default generated file in /config, and this file contains only visual settings.
i've checked in the /defaultconfigs/ folder, but there is no file in this folder.

it should be interesting to modify the amount of food needed to get a certain amount of hearts. (si if y want to get 2 hearts for 10 foods, or 1 heart for five, or something else, i can do it.)

idk if it's already possible, because i have no config file in defaultconfigs. so is it possible to find a model of this config file ?

**Comment by juliand665** [comment]
this is covered near the bottom of the description on curseforge:
> In post-1.12, Forge switched to a new config system, which means SoL: Carrot has two places to configure it now. The client-side configs (like visual options) are in the regular config folder and aren't synced between server and client. The server-side configs (like milestones or the blacklist) are stored in a serverconfig folder within each save and synced to the client. You can provide default values for these by placing a copy in the defaultconfigs folder, i.e. at defaultconfigs/solcarrot-server.toml.

**Comment by Bass2style** [comment]
the problem is that i play in a Single Player world, and that the server config is not generated, the mod should generate it by default, but it's not the case.

**Comment by juliand665** [comment]
it should absolutely be generated. located within your world’s folder under “saves/<your world name>/serverconfig/solcarrot-server.toml”

**Comment by Bass2style** [comment]
it's well generated under /<instance>/saves/<world>/serverconfig/
i whas searching in /<instance>/serverconfig/

thanks finding that out..
