### ISSUE TITLE
Upon death, extra hearts are added when using the Scaling Health mod

### ISSUE THREAD

**Issue by Camawama** [Cazsius/Spice-of-Life-Carrot-Edition#89]
#Versions

- Spice of Life Carrot Edition: solcarrot-1.15.2-1.9.4.jar
- Scaling Health: ScalingHealth-1.15.2-3.0.3+52.jar (latest)
- Silent Lib: SilentLib-1.15.2-4.6.0+48.jar (latest)

- Forge: forge-31.1.44
- Modpack: My own modpack https://www.curseforge.com/minecraft/modpacks/vanilla-plus-by-cama
- Optifine Installed: No

 Expected Behavior
I should be able to die without gaining hearts

## Actual Behavior
Whenever I die, the amount of extra hearts I have from the spice of life mod duplicates and I gain even more permanent hearts

## Steps to Reproduce the Problem

1. Run my modpack (Vanilla Plus)
2. Eat some new foods so you gain extra hearts
3. /kill (as many times as you want)
4. Observe the fact that you now have more permanent hearts

**Comment by juliand665** [comment]
Did you report this to Scaling Health? [Our logic for handling max health](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/blob/1.15/src/main/java/com/cazsius/solcarrot/tracking/MaxHealthHandler.java) is very simple and self-contained, so if anything, it's probably them doing something weird, considering their mod is all about modifying max health.

**Comment by Camawama** [comment]
I contacted both just to be sure: https://github.com/SilentChaos512/ScalingHealth/issues/257

**Comment by Camawama** [comment]
SilentChaos512 fixed the bug on his end so it works now! Sorry to bug you about this, I didn't know which mod was at fault. Thank you for this amazing mod!
