### ISSUE TITLE
1.12 version does not run in 1.12.

### ISSUE THREAD

**Issue by NicMoore88** [Cazsius/Spice-of-Life-Carrot-Edition#9]
I downloaded the 1.12 verison from the Twitch launcher.  Upon starting the game, I get a notification that it requires 1.12.1.  Really looking forward to trying this out.
Version 1.2.0
Forge 14.21.1.2443

**Comment by Cazsius** [comment]
The file is tagged for 1.12.1, you can just use version 1.12.1 instead of 1.12 to play, shouldn't be any changes to cause problems, will tag the mod for 1.12 next release
