### ISSUE TITLE
"Not Yet Eaten Bug" when eating food. Configs default

### ISSUE THREAD

**Issue by erwin1234777** [Cazsius/Spice-of-Life-Carrot-Edition#90]
https://imgur.com/a/WMohPkv gif of the problem occurring .
ill be listing all the mods in the screenshots below, i couldn't force the game to crash and provide me a modlist instead.

https://imgur.com/ZUrMbS2
https://imgur.com/LQo6FPY
https://imgur.com/Lsppa6L

this is also the latest log from the same instance the gif was running on, hopefully it might give some extra info.
[latest.log](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/4541105/latest.log)

**Comment by juliand665** [comment]
Does this still happen with just SoL: Carrot? If not (which is likely), can you try it with less and less mods until you find the smallest combination of mods that is sufficient to cause this issue?

**Comment by erwin1234777** [comment]
i'll give it a try

**Comment by juliand665** [comment]
feel free to comment if you happen to have any updates for this; closing until further input
