### ISSUE TITLE
(1.15.2)  Food milestones issue

### ISSUE THREAD

**Issue by Georg255** [Cazsius/Spice-of-Life-Carrot-Edition#92]
Can't seem to adjust food milestones.  A .cfg file for clients is generated but the food milestones option seems to be in server version and it's not editable ingame.  Can't find the server version in the config folder, either (not as .cfg or .toml).  Did I do something wrong?

**Comment by juliand665** [comment]
Please read the second note in the description on CurseForge carefully.

**Comment by Georg255** [comment]
I see it now.  Didn't know Forge decided to overly complicate things (switched to 1.15.2 recently from 1.12.).  Thank you for being polite about it.
