### ISSUE TITLE
serverconfig blacklist question

### ISSUE THREAD

**Issue by Rictu5** [Cazsius/Spice-of-Life-Carrot-Edition#93]
I'm trying to add all the uncraftable foods still appearing in the book in the blacklist but the following syntax is not working and result in a crash when starting the server.

```
#Foods in this list won't affect the player's health nor show up in the food book.
blacklist = [<vanillafoodpantry:wild_mashed_tatoes>]
```

Is my syntax wrong or the issue on vanilla food pantry side?

[latest.log](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/4567459/latest.log)

**Comment by juliand665** [comment]
It looks like you're mixing up the 1.12 (.cfg) and 1.15 (.toml) config syntaxes, resulting in something that doesn't make sense in either system, lol.

**Comment by juliand665** [comment]
[This](https://github.com/toml-lang/toml#user-content-array) should help.
```
blacklist = ["vanillafoodpantry:wild_mashed_tatoes"]
```
(also is it intentionally called "wild_mashed_tatoes" and not "wild_mashed_potatoes"?)

**Comment by Rictu5** [comment]
Thanks!
(Yes, it's the way the item is registered)
