### ISSUE TITLE
A crash occurs when you remove a mod with food you've eaten or blacklist an item that you've eaten.

### ISSUE THREAD

**Issue by Username2-stack** [Cazsius/Spice-of-Life-Carrot-Edition#94]
In 1.14.4, version 1.9.5:
When you remove a mod with food you've eaten:
[crash-2020-05-20_16.14.34-server.copy.txt](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/4671884/crash-2020-05-20_16.14.34-server.copy.txt)
When you blacklist an item you've eaten:
[crash-2020-05-23_10.07.25-server copy.txt](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/4671886/crash-2020-05-23_10.07.25-server.copy.txt)

**Comment by juliand665** [comment]
Oh, I'm an idiot. Try this:
[solcarrot-1.14.4-1.9.6.jar.zip](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/4672065/solcarrot-1.14.4-1.9.6.jar.zip)

**Comment by Username2-stack** [comment]
That does fix the first problem, though not the second.

**Comment by juliand665** [comment]
The second problem looks like it's on your end: your config file is failing to parse. Perhaps you need to surround it in quotes or something? `"vanillafoodpantry:earthwormspurged"`

**Comment by Username2-stack** [comment]
Oh, okay. Thanks, that fixed the problem.
