### ISSUE TITLE
[Enhancement request] Lunchbox

### ISSUE THREAD

**Issue by AngleWyrm10** [Cazsius/Spice-of-Life-Carrot-Edition#96]
The original Spice of Life has a real handy lunch box, a type of backpack for food that can be used to eat an appropriate amount when hungry. It made carrying food less of a chore because I didn't have to open a backpack and move stuff between inventories whenever I got hungry.

**Comment by juliand665** [comment]
See #44—really nowhere near as useful with this mod as with the original SoL, and while it might be nice to have, that makes it simply out of scope, more appropriate as a separate mod.
